### ISSUE TITLE
Can you add select option to setting  text or icon move to right panel?

### ISSUE THREAD

**Issue by ousui** [nls1729/acme-code#10]
Can you add select option to setting  text or icon move to right panel?
The final like this

![image](https://cloud.githubusercontent.com/assets/2839512/16906967/ad6a3ee6-4c84-11e6-9d04-49af0fcd6d07.png)

**Comment by nls1729** [comment]
I will look at the code and see if its possible.   (1)  The Hot Corner should remain in the left corner.      (2) The Conflict Detection is tied to the left corner and would not be allowed when the Activities Button is in the right corner. With the exception of (1) and (2) I think it can be done.

**Comment by nls1729** [comment]
If you are using version 3.16, 3.18, or 3.20 of the Gnome Shell, I can add the option to move the Activities Icon Button to the far right side of the panel as you requested.  I maintain the extension to be compatible with the latest stable version of the Gnome Shell and the two prior versions.  Let me know which version you are using.

**Comment by ousui** [comment]
GNOME Shell 3.20.3

Thank you.

**Comment by nls1729** [comment]
The updated extension has been uploaded to "https://extensions.gnome.org/".
It will take a few days for it to pass through the review process.  When it is accepted and available for install from ego, I will comment on the extensions.gnome.org website and post here.
I have attached a zip file of the updated extension with this post.  You can download it and install it with the tweak tool if you wish.

[activities-config@nls1729.zip](https://github.com/nls1729/acme-code/files/373908/activities-config.nls1729.zip)

Thank you for your request.  
Enjoy.
Norman

**Comment by nls1729** [comment]
The updated extension has been accepted at "https://extensions.gnome.org/".  The update can be installed at https://extensions.gnome.org/extension/358/activities-configurator/ .  I will close this issue in three days.

Norman

**Comment by ousui** [comment]
It's so cool, thank you Norman!
