### ISSUE TITLE
Enable "Do not disturb" mode with keyboard?

### ISSUE THREAD

**Issue by krlmlr** [nls1729/acme-code#13]
Key bindings would be nice.

**Comment by nls1729** [comment]
Your suggestion is now on my to-do list.  I should be able to get to it in the next couple of weeks.
Thank you.

**Comment by nls1729** [comment]
Version 7 of the extension is available.  A key binding preference has been added.
See https://nls1729.github.io/donotdisturb_button.html

**Comment by krlmlr** [comment]
Awesome, thanks! Super+Q was not taken on my system, in case you'd be looking for a default.
