### ISSUE TITLE
donotdisturb-button: Add an option to move the button to System status area

### ISSUE THREAD

**Issue by thanostx** [nls1729/acme-code#16]
It would be nice to have an option in Preferences to move the button on the right (System status area).

**Comment by nls1729** [comment]
Your request will be implemented.  I will let you know when it is available.

**Comment by nls1729** [comment]
I have attached a zip file here.  Please give it a try and let me know if this suits your needs.   I have not submitted to the extension website yet.
[donotdisturb-button@nls1729.zip](https://github.com/nls1729/acme-code/files/586857/donotdisturb-button.nls1729.zip)

**Comment by thanostx** [comment]
Works as expected. Thank you for this quick enhancement!

**Comment by nls1729** [comment]
Thanks for the translation.  I will close this issue when the updated extension passes review on the ego website.

**Comment by nls1729** [comment]
The updated extension is now available on https://extensions.gnome.org/ .
Thanks for opening this issue and again for the translations.

Regards,
Norman
