### ISSUE TITLE
Listed address for the Free Software Foundation is out-of-date

### ISSUE THREAD

**Issue by terrycloth** [nls1729/acme-code#18]
This is a very minor issue. But one or a couple places in your repo, the copyright comment at the beginning of a code file mentions getting a copy of the the GPL by sending snail mail to the Free Software Foundation. The FSF address you provide is a little out-of-date, as they've moved from Temple Place to Franklin Street. The current address is here:

> Free Software Foundation  
51 Franklin Street, Fifth Floor  
Boston, MA 02110-1335  
USA

https://www.fsf.org/about/contact/

Or you could just direct them to the web version instead:

https://www.gnu.org/licenses/old-licenses/gpl-2.0.html

**Comment by terrycloth** [comment]
Even I only noticed because I'm packaging your extensions for Fedora, and rpmlint detected the old FSF address ;P

**Comment by nls1729** [comment]
Thanks.  I will correct the addresses.

Regards,
Norman

On Tue, 2016-11-22 at 23:58 -0800, Andrew Toskin wrote:
> > > > > > This is a very minor issue. But one or a couple places in your repo,
the copyright comment at the beginning of a code file mentions
getting a copy of the the GPL by sending snail mail to the Free
Software Foundation. The FSF address you provide is a little out-of-
date, as they've moved from Temple Place to Franklin Street. The
current address is here:
> 
> Free Software Foundation
> 
> 51 Franklin Street, Fifth Floor
> 
> Boston, MA 02110-1335
> 
> USA
> 
> https://www.fsf.org/about/contact/
> Or you could just direct them to the web version instead:
> https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 
> 
>   
>   
> 
> 
> 
> 
> 
> 
> > > > > > > > > > > > > {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c5
5493e4bb","name":"GitHub"},"entity":{"external_key":"github/nls1729/a
cme-code","title":"nls1729/acme-code","subtitle":"GitHub
repository","main_image_url":"https://cloud.githubusercontent.com/ass
ets/143418/17495839/a5054eac-5d88-11e6-95fc-
7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent
.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-
b52498112777.png","action":{"name":"Open in
GitHub","url":"https://github.com/nls1729/acme-
code"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Liste
d address for the Free Software Foundation is out-of-date
(#18)"}],"action":{"name":"View
Issue","url":"https://github.com/nls1729/acme-code/issues/18"}}}

**Comment by nls1729** [comment]
I have updated the copyright statements.  If you find anything else let me know.  I will leave this issue open until I get the extensions uploaded and reviewed on the ego website.  I am curious which extensions are you packaging?

**Comment by terrycloth** [comment]
> I have updated the copyright statements.

Great, thanks.

> I am curious which extensions are you packaging?

Do Not Disturb Button and Activities Configurator. I've liked using these for a little while now, and I thought some GNOME Shell extensions would be a nice place to start when learning about RPM packaging. Also, as I understand it, Max Window Effect is already a feature included in Activities Configurator. I'm considering doing the ones for reloading the Shell or extensions, but it's mostly only useful for extension developers, so I haven't personally needed them yet.

https://bugzilla.redhat.com/show_bug.cgi?id=1390477  
https://bugzilla.redhat.com/show_bug.cgi?id=1397692

**Comment by nls1729** [comment]
Good luck with your packaging. I am closing this issue.
