### ISSUE TITLE
Activities Configurator: rpmlint complains about empty file.

### ISSUE THREAD

**Issue by terrycloth** [nls1729/acme-code#20]
Still working here and there on my first RPM packages for Fedora.

This is maybe a little pedantic... But `stylesheet.css` is empty. Did you mean to delete it, or are you just keeping it around in case you want to add styles later? Just curious.

**Comment by nls1729** [comment]
The stylesheet.css is a file created in 2012 by the build system I used for the original version of the extension.  I will fix my current makefile to not include it.

**Comment by terrycloth** [comment]
It's fine, you can keep it. I've been appending a comment so that rpmlint doesn't print the warning. I just thought I'd check to make sure you *meant* to keep it, is all.

**Comment by nls1729** [comment]
I removed stylesheet.css it was there because it was there for no good reason.  When it is not needed you should not have to handle the exception.

**Comment by nls1729** [comment]
I re-named the mo files and made a few changes to insure the settings worked if installed from a rpm for activities-config and donotdisturb-button.  I tested by removing the locale and schema directories from the local extension directory for each extension.  I copied the mo files to the proper shared locale directory and the schema xml files to /usr/share/glib-2.0/schemas and recompiled the shared gschemas.compiled file.  This should simulate extensions installed from a rpm. Both extensions functioned properly. The zips have been uploaded to the ego site for review.  I have updated the github repo.  I will leave this issue open for a few weeks in case you find any problems.

**Comment by terrycloth** [comment]
Cool. Just to be clear, will you be uploading the zips to nls1729.github.io after the review on EGO?

**Comment by nls1729** [comment]
nls1729.github.io was updated this AM.  Please note the extension zipfiles are downloaded from the extension website.  The zips on nls1729.github.io are simply links to ego files. It is the best way to insure users get the reviewed extension.  Good luck with your rpms.  I will leave this issure open for a few weeks in case you find any problems.

**Comment by terrycloth** [comment]
Both packages have pushed to the stable (updates) repository, and install and run fine on my computer.
