### ISSUE TITLE
Rename the language files in source tarball releases.

### ISSUE THREAD

**Issue by terrycloth** [nls1729/acme-code#21]
When installing an extension for a single user only, language files would normally appear in `locale/` under the extension's directory under `~/.local/share/gnome-shell/extensions/`. Most packaged GNOME Shell extensions in Fedora, however, install these translations to a global directory. So, in the installed RPM package, a .mo file would have a path like this:

```
/usr/share/locale/de/LC_MESSAGES/nls1729-extensions.mo`
```

The `nls1729-extensions` filename seems to be the same for both Activities Configurator and Do Not Disturb Button, so the two packages are going to conflict. I tried simply renaming the .mo files from my RPM spec, but then the extension configurator doesn't seem to get translated. So I believe I need you to rename the .mo files when you prepare your source releases.

**Comment by nls1729** [comment]
This should be easy to fix.  I will look at it this weekend.

**Comment by nls1729** [comment]
Closing see issue 20.
