### ISSUE TITLE
[Activities Configurator] Hot corner behavior when drag-n-dropping broken on Wayland

### ISSUE THREAD

**Issue by Jehan** [nls1729/acme-code#28]
Hi!

I was testing stuff on Wayland (Fedora 26) and realized that the hot corner behavior which works when drag-n-dropping (even when hot corner is disabled) doesn't work under Wayland. It still works fine under X11.
As reminder this feature was added in commit c632edc4b1a0732a00556ccd7d4f1d8429108e51 and that's very useful because I really dislike the hot corner except when I drag-n-drop. :-)
Thanks!

**Comment by nls1729** [comment]
Thanks for your report.

I installed f26 beta on a test system.  I did not use a live CD.  I did a network install to get all the available updates.

With the hot corner enabled the drag and drop works if I can go to the Overview with the mouse on my test system.  If the Hot Corner Threshold is set too high it may not switch when dragging into the corner. 

In Wayland with the hot corner disabled I cannot drag and drop through the hot corner.  I will look into the problem.  As a workaround you can do the following:

1.  Drag the item from the application into open space on the current workspace.
2.  Use the Super (or Windows) key to open the Overview.
3.  Drag the item to the other application as usual.

I will let you know if I can fix it.

**Comment by nls1729** [comment]
nCorrection f26 beta should be f27 beta.  I tested on f26 and f27.  Under Wayland I have found no way to drag and drop via the hot corner when it is disabled.  The Super Key looks like the only way to go from the desktop to the Overview.  I have not given up and will spend some more time on the problem,

**Comment by Jehan** [comment]
Ok. Hopefully you'll find a solution because I would really miss the feature a lot. Thanks for all the work!

**Comment by nls1729** [comment]
I have no problem with drag and drop in Wayland if the hot corner is not disabled.
Activities Configurator version 58
XDG_SESSION_TYPE=wayland
4.13.11-200.fc26.x86_64
GNOME Shell 3.24.3

I have been unable to find a way to drag and drop through the hot corner in Wayland if the corner is disabled. There is not a signal exposed that I can use to determine if the drag is in progress when attempting to enter the hot corner. Please take a look at the video in the zip file. 
< https://drive.google.com/file/d/1ID_ilxevRoG2UARhUOO2CwMId94G7mQj/view?usp=sharing >
Let me know what you think.

**Comment by Jehan** [comment]
> Please take a look at the video in the zip file.

I watched the video. If I understand, you are proposing to just hit the Super key to switch the desktop while dragging? I know about this as this works by default this way and this is how I do it most of the time actually.
But I would still want to have the no-keyboard alternatives since there are times where I like to be able to do the same thing all with the pointer only. There are times where the keyboard is not practical at all and that were the times I was targetting.

Probably we could make a bug report on GNOME so that it provides the appropriate signal on Wayland as well. AFAIK there is no reason to have behavior inconsistency depending on whether your backend is X or Wayland.

**Comment by nls1729** [comment]
Before we open a bug report let me look at the code some more.  Since the drag and drop works when the hot corner is not disabled there may be a way to make the extension work. I will try to get a better understanding of how the X dnd code works.  It may take a week or two to find it or give up.  If I can't fix it a bug report is the next step.

**Comment by nls1729** [comment]
I found away to switch the Overview.

If the mouse pointer enters the Activities Button an Enter signal is emitted and a Leave signal is emitted when the pointer leaves. If the primary mouse button is normal no Motion signals are emitted by mouse movement inside the Activities Button. If the primary mouse button is pressed and held without an item being dragged the Enter and Leave signals are emitted and no Motion signals are emitted.

If the primary mouse button is pressed and held with an item being dragged the Enter and Leave signals are emitted and Motion signals are emitted. This gives me enough information to know that I can use the first Motion signal emitted to start a timer that upon expiration will switch to the Overview for the drag to continue. If the pointer leaves the Activities Button prior to the expiration of the timer I simply reset the timer and nothing happens. I have set the timer for 750 ms. I think it is short enough not to be noticeable for an intended switch to occur and long enough to not falsely switch to the Overview inadvertently.
So to drag and item from the Desktop to the Overview, drag the item in the the Activities Button and 3/4's of a second later the Overview will switch and you can continue to drag.

Please test the attached and let me know what you think.

https://drive.google.com/file/d/14Is07D5h_RRgkSxQsmfJUD6d2caMBfL1/view?usp=sharing

**Comment by nls1729** [comment]
Hello Jehan,

The zip file at the following link has been uploaded to the extesnions.gnome.org for review.
https://drive.google.com/file/d/1jg_ZguechHSge3OkYjvF2_QtFniDl1_d/view?usp=sharing

It has a few changes additional changes that affected X11 sessions and Wayland sessions with the Hot Corner disabled.  The extension has been tested in Fedora 26, Fedora 27 and Ubuntu 17.10 in Wayland and X11 sessions with the Hot Corner enabled and disabled.

I will comment here when the extension passes review and is available from the website.

**Comment by Jehan** [comment]
Hi nls1729!

Sorry for not answering immediately. I was working on setting up a new machine lately for someone else. Anyway I tested, and it works great. As far as I can tell, the current behavior seems quite acceptable.

**Comment by nls1729** [comment]
Activities Configurator version 61 is available at ego website. Thanks for your patience.
