### ISSUE TITLE
donotdisturb-button: Disable notification sounds when busy

### ISSUE THREAD

**Issue by badshah400** [nls1729/acme-code#30]
It would be great if the donotdisturb-button disabled notification sounds when in the busy mode. At present, toggling on the busy mode does hide the notification banner from appearing, but I can still hear the "Alert" sound from the GNOME sound theme (which I *do* want to hear when I am not in the busy mode).

Thanks for the exceedingly useful extension.

**Comment by nls1729** [comment]
@badshah400 
What linux distribution are you using?
I have tested using Gnome Shell 3.26 on Fedora and the sounds are blocked when the extension is in the busy state.

**Comment by badshah400** [comment]
I am using openSUSE Tumbleweed, Gnome shell 3.26.2.

**Comment by nls1729** [comment]
@badshah400 
Please try the following and let me know the results.
Set the extension to Busy.
At a terminal prompt:
$ notify-send --hint=string:sound-name:message XXX YYY
Set the extension to Available.
$ notify-send --hint=string:sound-name:message XXX YYY

**Comment by badshah400** [comment]
@nls1729 Sorry, it does mute the usual notification sound. The sound that is not muted is the empathy chat notification (and possibly non-standard notification sounds from other assorted apps), but that probably has nothing to do with your extension. I regret that I misunderstood this and apologise if I wasted your time.
