### ISSUE TITLE
Activities configurator disables GNOME's 3.26 auto transparency top panel

### ISSUE THREAD

**Issue by joca-bt** [nls1729/acme-code#33]
Using activities configurator with default settings makes the top panel not have the new auto transparency introduced in GNOME 3.26. Enabling 'Enable Conflict Detection' does not solve the issue.

**Comment by nls1729** [comment]
I did not receive an email notification of this issue.  I will look into it as soon as I can find the time.

**Comment by nls1729** [comment]
I don't see an issue the extension provides more control over the panel transparency and color than the new feature in GS 3.26 which gives no user control.  The extension has an option to change the top bar to opaque when a window is maximized.
