### ISSUE TITLE
What about GNOME 3.28 support?

### ISSUE THREAD

**Issue by Kerrung** [nls1729/acme-code#35]
Hi! Thank you very much for your great work! But what about GNOME 3.28 official support?

**Comment by nls1729** [comment]
As soon as I can get a test system setup I will test GS 3.28.  I will post here when I complete the testing.

**Comment by nls1729** [comment]
I have begun testing.  If you use Ubuntu you may be interested in comments in issue #34.

**Comment by Kerrung** [comment]
>I have begun testing. If you use Ubuntu you may be interested in comments in issue #34.

I'm using Arch Linux.

**Comment by Kerrung** [comment]
Thank you! Fixed
