### ISSUE TITLE
activities-config breaks on Ubuntu 18.04

### ISSUE THREAD

**Issue by frenetic** [nls1729/acme-code#37]
Hi there. I just installed Ubuntu 18.04 and decided to give your extension a try.

It gives me the following error (screenshot appended)

```
Error: Requiring Clutter, version none: Typelib file for namespace 'Clutter' (any version) not found

Stack trace:
  @/home/frenetic/.local/share/gnome-shell/extensions/activities-config@nls1729/colors.js:1:7
  @/home/frenetic/.local/share/gnome-shell/extensions/activities-config@nls1729/prefs.js:15:7
  _getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:75:13
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:90:31
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _extensionFound/<@resource:///org/gnome/shell/extensionPrefs/main.js:206:13
  main@resource:///org/gnome/shell/extensionPrefs/main.js:397:5
  @<main>:1:43
```

![image](https://user-images.githubusercontent.com/122976/39399471-7f4bf610-4af4-11e8-9130-60fdb71c744b.png)

**Comment by nls1729** [comment]
To fix the problem do the following:
Delete line 15 in the file prefs.js, "const Colors = Me.imports.colors;".

The bug was fixed and uploaded to the extension website,  https://extensions.gnome.org ,  two weeks ago.  The updated extension has not been reviewed and released yet. 

Let me know  how it goes.

**Comment by Xenya0815** [comment]
I had the same problem. After I removed line 15 it runs like a charm. Thanks!

**Comment by nls1729** [comment]
Fixed in April.
