### ISSUE TITLE
Handle touch events on wayland

### ISSUE THREAD

**Issue by badshah400** [nls1729/acme-code#38]
Do not disturb button is unresponsive to touch on wayland (gnome-shell 3.28). To fix this, the code needs to handle `CLUTTER_TOUCH_BEGIN/UPDATE/END.`

See comment here:
https://bugzilla.gnome.org/show_bug.cgi?id=770185#c21
and how gnome-shell does this for its top bar (as an example):
https://gitlab.gnome.org/GNOME/gnome-shell/merge_requests/112/diffs

Many thanks for the excellent extension.

**Comment by nls1729** [comment]
I should have responded to this issue earlier but I have not had time to address it .   I have a family member who is experiencing a serious health issue which has required my attention.      

Version 24 of the extension is available at: 
https://extensions.gnome.org/extension/964/do-not-disturb-button/

I do not have a device that generates TOUCH events.  Please install version 24 and let me know how it goes.

Thanks for reporting the issue.
Norman

**Comment by badshah400** [comment]
Thanks a bunch, Norman! It works great now. I did have to log out and log back in after upgrading the extension for it to start recognising touch events; however, since then no problems.

My best wishes for you and your family.
