### ISSUE TITLE
Rename Activities Configurator to Panel Configurator

### ISSUE THREAD

**Issue by francoism90** [nls1729/acme-code#4]
It does so much more than configuring Activities.
I think Panel Configurator suits better. :)

Also it would be nice to configure (restore, hide, change size?) the icon background for the active app.

**Comment by nls1729** [comment]
I considered your suggestion to rename the extension.

Changing the name of an extension presents practical problems.  The extension is known by its name and UUID.  Changing the name would be confusing to users who have used the extension for several iterations of the Gnome Shell.  There are three current versions of the extension available on the extension website.  There is a version for Gnome Shell [ 3.8 3.10 3.12 3.14 3.16 ],
a version for 3.6 and a version for 3.4.  To change the name would require updating the extension website with essentially duplicate extensions.  That is not a good idea.  I agree with you that the extension does provide features for other parts of the panel beyond the Activities Button, but I have tried to cover that with the description.    The description includes a reference to the panel. "Configure the Activities Button and Panel appearance with the Activities Configurator Extension and Gnome Shell Extension Preference Tool."  I can see only problems with a name change.  If I had known how the extension would evolve I may have considered a different name.  I always value input from others.  It makes me think which is a good thing.


"Also it would be nice to configure (restore, hide, change size?) the icon background for the active app."

I am not sure of what you mean.

The  App Menu Button's  menu content is controlled by the application or if no menu is provided by the application, a default "Quit" entry is supplied by the Shell.  If you are referring to the window operations of Show (restore), Minimize (hide) and Resize (size), these functions and sometimes more are provided by the application (or the Overview in the care of (restore)).  I don't see any possible changes to the App Menu Button as it belongs to the application and should always be visible for access to the app's menu.

**Comment by francoism90** [comment]
Thanks for your reply and the information. :)

Seems changing the name can cause (big) issues; better not renaming it. ;)
The name is not so bad, but I as user didn't know it also could customize the panel. :)

This is what I mean about the second request: https://drive.google.com/file/d/0BzfSuVpNNRzqZmtEaFotVnVfa1k/view?usp=sharing

I'm using Arc as the Shell-theme, that does disable the (app-icon) background image.
Don't know if it is possible, but would be nice if it could be overwritten with a simple extension (instead of editing the css file).

Thanks. :)

**Comment by nls1729** [comment]
I looked at the Panel code and the Arc Theme css.  I think I can accomplish what you want.  I will experiment a bit. If I can find a reasonable solution I will implement it as an option in the Activities Configurator.  It may take a few days for me to find the time to do the code.

**Comment by francoism90** [comment]
Thanks! :)

Remember it's not that of high priority, I'm even 'not mad' if the feature doesn't end up in the extension at all. ;P

**Comment by nls1729** [comment]
I have not forgotten this issue.  I have the code done for this issue and will include it in the next release for GS 3.14 and 3.16.  I am working on making the extension touch screen friendly and a couple of other minor things.  I hope to have it done in a week or two, free time permitting.

**Comment by francoism90** [comment]
Cool :D :+1: 

Keep up the good work.

**Comment by nls1729** [comment]
François M.:
Jehan:

I have updated the Activities Configurator for GS 3.14 and 3.16 with the following:

Added code to be touch screen friendly.  I can't test it but looking at the existing Shell's code I believe it will work.

Added the option to not display the icon for the currently focused application in the Application Menu Button on the left of the panel.

Changed the behavior of the hot corner when it is disabled.  Dragging an item into the hot corner will display the overview and continue the drag.  This is the default behavior for the hot corner when it is enabled.

I have not uploaded the extension for review yet.  
If you would like to test for me please send me an email via the email link at:
https://nls1729.github.io   
I will send you a zip file of the extension which can be installed with the Tweak Tool.

Thanks,
Norman

**Comment by nls1729** [comment]
I just got an email from Jehan who said he sent an email four days ago which I did not receive.  Just checking, did you get the email I sent four days ago?

**Comment by francoism90** [comment]
Yep! Sorry, haven't found the time to debug/provide you with feedback.

Hope to provide you with feedback at the end of this week.

**Comment by francoism90** [comment]
Hello Norman,

Sorry for this late reply, but I haven't found the time to provide you with
any good feedback.
If you still want me to do testing, please let me know.

Thanks, and also for updating your extension to GS 3.18.

Best regards,


Met vriendelijke groet,

François Menning

**Comment by nls1729** [comment]
Hello François,

No one can ever find time to do everything. This stuff is done for free.  The schedule is deterimed by how much play time we can find. I am glad to hear from you. If you can test with a touchscreen device there are four functions you can test that would be very helpful

1.  A tap on the Activities Text or Icon should display the overview (like a primary mouse click, left button for a right handed person).
2.  A tap and hold for 500ms+ on the Activities Text or Icon should display the Gnome Shell Extensions tool for enable/disable and preferences (like a secondary mouse click, right button for a right handed person).
3.  With the hot corner disabled,  touch drag and drop an item through the hot corner to the overview.  I test this function with the mouse by going to the second workspace and starting the image viewer. Then return to the first workspace open Files to a directory that contains an image.  Drag the image through the hot corner into the overview and then into the second workspace onto the image viewer when the image viewer is displayed in the overview drop the image into the image viewer.
4.  The preferences for the Activities Configurator uses Gtk3 widgets which should work with a touchscreen reasonably well. You should be able to press a button, select the text entry, slide a scaler, and scroll the window with touch gestures.

Your interest and efforts are much appreciated.
Thanks,
Norman

**Comment by nls1729** [comment]
I am closing this issue.  Let me know if all is not well.

**Comment by francoism90** [comment]
Many thanks Norman!

The updates are working perfectly here on Gnome 3.20. :)
