### ISSUE TITLE
Override shell theme disable (greyed out)

### ISSUE THREAD

**Issue by sakxdehr** [nls1729/acme-code#40]
Hello,

Have the latest version of activities configurator installed from extensions.gnome.org (Commit: fa3a78b5c47cbf615ce2346f6f061e3a28f4eaec).

When I initially installed the extension I was able to turn on "Override Shell Theme" but now it is disabled and greyed out so I am unable to enable it.

System:

Linux 4.9.0-7-amd64 #1 SMP Debian 4.9.110-3+deb9u1 (2018-08-03) x86_64 GNU/Linux
GNOME Shell 3.22.3
Kali-X Shell Theme.

I have another machine that has the exact same OS, gnome shell version and shell theme and I **am** able to enable the override setting. So not sure what the issue is. I have tried to reinstall the extension but this has not fixed the issue.

Is there anything you could recommend I try?

Your response is greatly appreciated. Thanks.

**Comment by nls1729** [comment]
Examine the gsettings entry /org/gnome/shell/extensions/activities-config shell-theme-id with the dconf Editor or from the command-line with:

gsettings get org.gnome.shell.extensions.activities-config shell-theme-id

It should display the theme name and current session mode something like  'TRANSPARENTWORKSPACE<|>user'

Let me know what you see.

**Comment by nls1729** [comment]
Did you get a notification of my prior comment concerning "Override shell theme"?

**Comment by sakxdehr** [comment]
Sorry for whatever reason emails were getting caught in spam. Sorted now.

I see:

null<|>user

I have noticed the setting override-theme = false. When looking at that setting I see a message about "No schema available. The application that installed this key may have been removed" with a button to "Erase Key".

Ignoring that message if i set this option to "true" the override works.

**Comment by nls1729** [comment]
In your initial comment you indicated you have Kali-X Shell Theme installed and you could turn on "Override Shell Theme" in the past, but now it is disabled and greyed out.

It appears there is a problem with the User Theme feature in your Gnome Shell installation.  

“null<|>user” indicates there is no user theme installed.  The null should be the name of the user theme.

Please check the following:

Right click the Activities area at the top left corner to display the Shell Extensions tool.

Is the User Themes extension listed and is it ON?  For the Activities Configurator to function properly the User Themes extension must be installed and be enabled (ON).

Is the  Kali-X Shell Theme installed in the “.themes” directory in your home directory?

You might find this useful.
https://itsfoss.com/install-switch-themes-gnome-shell/

Let me know what you find and we will go from there.

**Comment by sakxdehr** [comment]
User themes is enable and Kali-X theme is working. It is installed in /usr/share/themes

If I remove it from there and install it in ~/.themes org.gnome.shell.extensions.activities-config shell-theme-id shows Kali-X<|>user but the Override Shell Theme option is still greyed out. However, I then can't activate the option manually. Which is what I have been relying on at the moment.

Considering this works on a machine with identical os, theme, etc. I am going to do a reinstall since this system is setup to do it with relative ease. Will let you know the outcome.
