### ISSUE TITLE
The option "Show overview is no applications are running"  stops working after the system re-login or system reboot. 

### ISSUE THREAD

**Issue by Kerrung** [nls1729/acme-code#44]
Hi! Thank you so very much for your great work!
But the option "Show overview is no applications are running"  stops working after the system re-login or system reboot. If I re-enable this option, it starts working fine again, but it again stops working if then I reboot my system. This issue only happens if I use GNOME 3.30, but this has never happened before on GNOME 3.28 and all other previous versions of GNOME. I'm using Arch Linux.

**Comment by nls1729** [comment]
I tested the extension on GS 3.30 and could not reproduce the problem you are seeing.  I tested on a recent test build of Fedora 29.  Fedora will release a true beta version in a few days.  I will retest when the beta is available if we haven't found the problem by then.  

I have a few questions that may help us find the source of the bad behavior you are seeing.

1.  When you reboot or re-login is the option OFF or ON when you display the extension’s preferences to re-enable the option?  
2.  What is the version number of the installed extension?
3.  Did you install the extension from extensions.gnome.org or from  Arch AUR?
4.  What version do you see if you execute gnome-shell - -version on the command line?

Please create a new user and install the extension from extensions.gnome.org as that user.   Do not install or enable any other extensions for the new user. Then test with the new user.

Let know how it goes...

**Comment by Kerrung** [comment]
@nls1729 
1) ON
2 &3 ) [AUR git-version](https://aur.archlinux.org/packages/gnome-shell-extension-activities-config)
4) 
$ gnome-shell --version
GNOME Shell 3.30.0

**Comment by Kerrung** [comment]
It works fine for me with a new fresh user created. Probably it need to reset the extension settings.
Thank you.

**Comment by nls1729** [comment]
The user settings are stored in a file in your home directory ~/.config/dconf/user.  It is likely the file was damaged in some way causing the problem you observed.  If you want to use the original user directory you can rename the ~/.config/dconf/user file then log out and then login and a new user file will be created.  You then would need to re-set any user preferences.  I will leave this issue open for a few days in case you have any further problems.

**Comment by Kerrung** [comment]
@nls1729 my folder ~/.config/dconf is absolutely empty, so I haven't a "user" file. What I should to do?

**Comment by nls1729** [comment]
Logged in as the bad user look at the preferences for the extension.  If the version  at the top is not v66 install the extension from extensions.gnome.org and log out and log in and look for ~/.config/dconf/user.  I don't think the AUR version has been updated since v58. Let me know how it goes.

**Comment by Kerrung** [comment]
@nls1729 The AUR version is a git-version, so it is NOT a v58 as it noted. It means that it building from the latest source code from your GitHub repository.
And I tried to install a version of the extension from extensions.gnome.org but it's the same result, sadly.

**Comment by Kerrung** [comment]
@narzb 
$ ls -la ~/.config/dconf
total 211
drwxr-xr-x  2 user users  3488 Sep 14 00:38 .
drwx------ 50 user users  3488 Sep 13 19:29 ..
-rw-r--r--  1 user users 43956 Sep 14 00:38 user
-rw-r--r--  1 user users 25902 May  1 18:10 user.65M9HZ
-rw-r--r--  1 user users 25902 May  1 17:54 user.ABM8HZ
-rw-r--r--  1 user users 31059 May 25 16:59 user.IBCVJZ
-rw-r--r--  1 user users 38963 Aug  7 07:50 user.J17DNZ
-rw-r--r--  1 user users 31387 Jun  2 20:50 user.QY2YJZ


$ ls -Zal ~/.config
total 199
drwx------ 50 user users ?  3488 сен 13 19:29 .
drwx------ 29 user users ?  3488 сен 14 00:44 ..
drwxr-xr-x  2 user users ?  3488 сен 12 00:08 autostart
drwx------  3 user users ?  3488 апр  5 22:30 cef_user_data
drwx------ 21 user users ?  3488 сен 14 00:44 chromium
drwx------  2 user users ?  3488 сен  6 19:00 configstore
drwxr-xr-x  2 user users ?  3488 сен 14 00:45 dconf
drwxr-xr-x  3 user users ?  3488 авг 20 20:56 deadbeef
drwxr-xr-x  2 user users ?  3488 авг 18 00:04 Desktop
drwxr-xr-x  2 user users ?  3488 мая 14 02:56 dmMediaConverter
drwx------  2 user users ?  3488 июн 30 12:19 enchant
drwxr-x---  3 user users ?  3488 сен 13 13:28 epiphany
-rw-r--r--  1 user users ? 12137 апр 21  2016 .face
drwxr-xr-x  3 user users ?  3488 мая 14 02:57 ffmulticonverter
drwxr-xr-x  2 user users ?  3488 сен  8 20:21 gconf
drwx------  4 user users ?  3488 июн  6 23:02 geany
drwxr-xr-x  2 user users ?  3488 мар 31 06:50 gedit
drwxr-xr-x  3 user users ?  3488 сен  4 19:38 GIMP
drwx------  2 user users ?  3488 мар 31 07:45 gnome-appfolders-manager
drwxr-x---  4 user users ?  3488 июн  5 23:41 gnome-builder
d-w-r-xr-T  2 user users ?  3488 мар 31 06:36 gnome-control-center
drwxr-xr-x  3 user users ?  3488 мар 31 06:12 gnome-session
drwxr-xr-x  2 user users ?  3488 мар 31 06:34 goa-1.0
drwxr-xr-x  3 user users ?  3488 мая 20 15:58 google-chrome
drwxr-xr-x  3 user users ?  3488 мая 20 15:58 google-chrome-beta
drwxr-xr-x  3 user users ?  3488 мая 20 15:58 google-chrome-unstable
drwxr-xr-x  2 user users ?  3488 мар 31 23:55 green-recorder
drwx------  2 user users ?  3488 мая 19 14:34 gsconnect
drwxr-xr-x  2 user users ?  3488 сен  5 19:28 gthumb
drwx------  2 user users ?  3488 сен  5 19:28 gtk-2.0
drwx------  2 user users ?  3488 сен 13 17:23 gtk-3.0
drwxr-xr-x  2 user users ?  3488 мая 13 17:28 gtk-4.0
drwx------  3 user users ?  3488 мар 31 06:12 ibus
drwxr-x--x  7 user users ?  3488 авг  6 07:08 inkscape
drwxr-xr-x  3 user users ?  3488 мая 14 18:39 libreoffice
drwxr-xr-x  4 user users ?  3488 апр 22 22:42 lutris
drwxr-xr-x  3 user users ?  3488 мар 31 19:36 menus
-rw-r--r--  1 user users ?  1260 сен 12 00:36 mimeapps.list
-rw-r--r--  1 user users ?   560 May 14 02:28 monitors.xml
drwxr-xr-x  3 user users ?  3488 Mar 29  2017 mpv
drwxr-xr-x  2 user users ?  3488 Mar 31 14:54 nautilus
drwxr-xr-x  2 user users ?  3488 May 24 20:54 neofetch
-rw-r--r--  1 user root  ?    28 May 23 23:32 numix-folders
drwxr-xr-x  6 user users ?  3488 Sep  4 10:46 obs-studio
-rw-r--r--  1 user users ?   109 Sep 13 19:29 pavucontrol.ini
drwxr-xr-x  2 user users ?  3488 Apr  3 16:19 Public
drwx------  2 user users ?  3488 Apr  3 04:32 pulse
-rw-r--r--  1 user users ?     0 Aug 20 19:55 qt5ct
-rw-r--r--  1 user users ?   575 Sep  4 22:09 QtProject.conf
drwxr-xr-x  7 user users ?  3488 May  3 13:40 Signal
drwx------  7 user users ?  3488 Jun  6 00:35 sublime-text-3
drwx------  2 user users ?  3488 Srp  5 17:59 teamviewer
drwxr-xr-x  2 user users ?  3488 Aug  6 10:16 Templates
drwxr-xr-x  5 user users ?  3488 Aug  3 11:40 transmission
-rw-------  1 user users ?   664 May 25 11:03 user-dirs.dirs
-rw-r--r--  1 user users ?     5 Mar 31 06:12 user-dirs.locale
drwxr-xr-x  2 user users ?  3488 May  1 14:56 vlc
drwx------  9 user users ?  3488 Aug 29 23:28 Whatsie
drwx------  9 user users ?  3488 Sep  9 01:48 Wire


And when I deleted ~/.config/dconf it was immediately automatically recreated with a "user" file in this folder.

**Comment by Kerrung** [comment]
And when I deleted ~/.config/dconf it was immediately automatically recreated with a "user" file in this folder. Then I tried to re-enable the option, then reboot, but, sadly, it did't help to solve the issue.

**Comment by Kerrung** [comment]
And then I did it again:

$ ls -la ~/.config/dconf
total 51
drwx------  2 user users  3488 сен 14 01:13 .
drwx------ 50 user users  3488 сен 14 01:07 ..
-rw-r--r--  1 user users 43844 сен 14 01:13 user
[user@archlinux ~]$ 
[user@archlinux ~]$ 
[user@archlinux ~]$ 
[user@archlinux ~]$ ls -Zal ~/.config
total 199
drwx------ 50 user users ?  3488 сен 14 01:07 .
drwx------ 29 user users ?  3488 сен 14 01:08 ..
drwxr-xr-x  2 user users ?  3488 сен 12 00:08 autostart
drwx------  3 user users ?  3488 апр  5 22:30 cef_user_data
drwx------ 21 user users ?  3488 сен 14 01:13 chromium
drwx------  2 user users ?  3488 сен  6 19:00 configstore
drwx------  2 user users ?  3488 сен 14 01:13 dconf
drwxr-xr-x  2 user users ?  3488 сен 14 00:51 dconfOLD
drwxr-xr-x  3 user users ?  3488 авг 20 20:56 deadbeef
drwxr-xr-x  2 user users ?  3488 авг 18 00:04 Desktop
drwxr-xr-x  2 user users ?  3488 мая 14 02:56 dmMediaConverter
drwx------  2 user users ?  3488 июн 30 12:19 enchant
drwxr-x---  3 user users ?  3488 сен 13 13:28 epiphany
-rw-r--r--  1 user users ? 12137 апр 21  2016 .face
drwxr-xr-x  3 user users ?  3488 мая 14 02:57 ffmulticonverter
drwx------  4 user users ?  3488 июн  6 23:02 geany
drwxr-xr-x  2 user users ?  3488 мар 31 06:50 gedit
drwxr-xr-x  3 user users ?  3488 сен  4 19:38 GIMP
drwx------  2 user users ?  3488 мар 31 07:45 gnome-appfolders-manager
drwxr-x---  4 user users ?  3488 июн  5 23:41 gnome-builder
d-w-r-xr-T  2 user users ?  3488 мар 31 06:36 gnome-control-center
drwxr-xr-x  3 user users ?  3488 мар 31 06:12 gnome-session
drwxr-xr-x  2 user users ?  3488 мар 31 06:34 goa-1.0
drwxr-xr-x  3 user users ?  3488 мая 20 15:58 google-chrome
drwxr-xr-x  3 user users ?  3488 мая 20 15:58 google-chrome-beta
drwxr-xr-x  3 user users ?  3488 мая 20 15:58 google-chrome-unstable
drwxr-xr-x  2 user users ?  3488 мар 31 23:55 green-recorder
drwx------  2 user users ?  3488 мая 19 14:34 gsconnect
drwxr-xr-x  2 user users ?  3488 сен  5 19:28 gthumb
drwx------  2 user users ?  3488 сен  5 19:28 gtk-2.0
drwx------  2 user users ?  3488 сен 14 01:08 gtk-3.0
drwxr-xr-x  2 user users ?  3488 мая 13 17:28 gtk-4.0
drwx------  3 user users ?  3488 мар 31 06:12 ibus
drwxr-x--x  7 user users ?  3488 авг  6 07:08 inkscape
drwxr-xr-x  3 user users ?  3488 мая 14 18:39 libreoffice
drwxr-xr-x  4 user users ?  3488 апр 22 22:42 lutris
drwxr-xr-x  3 user users ?  3488 мар 31 19:36 menus
-rw-r--r--  1 user users ?  1260 сен 12 00:36 mimeapps.list
-rw-r--r--  1 user users ?   560 мая 14 02:28 monitors.xml
drwxr-xr-x  3 user users ?  3488 мар 29  2017 mpv
drwxr-xr-x  2 user users ?  3488 мар 31 14:54 nautilus
drwxr-xr-x  2 user users ?  3488 мая 24 20:54 neofetch
-rw-r--r--  1 user root  ?    28 мая 23 23:32 numix-folders
drwxr-xr-x  6 user users ?  3488 мая  4 10:46 obs-studio
-rw-r--r--  1 user users ?   109 сен 14 00:57 pavucontrol.ini
drwxr-xr-x  2 user users ?  3488 апр  3 16:19 Public
drwx------  2 user users ?  3488 апр  3 04:32 pulse
-rw-r--r--  1 user users ?     0 авг 20 19:55 qt5ct
-rw-r--r--  1 user users ?   575 сен  4 22:09 QtProject.conf
drwxr-xr-x  7 user users ?  3488 мая  3 13:40 Signal
drwx------  7 user users ?  3488 июн  6 00:35 sublime-text-3
drwx------  2 user users ?  3488 сен  5 17:59 teamviewer
drwxr-xr-x  2 user users ?  3488 апр  6 10:16 Templates
drwxr-xr-x  5 user users ?  3488 авг  3 11:40 transmission
-rw-------  1 user users ?   664 мая 25 11:03 user-dirs.dirs
-rw-r--r--  1 user users ?     5 мар 31 06:12 user-dirs.locale
drwxr-xr-x  2 user users ?  3488 мая  1 14:56 vlc
drwx------  9 user users ?  3488 авг 29 23:28 Whatsie
drwx------  9 user users ?  3488 сен  9 01:48 Wire

**Comment by nls1729** [comment]
Is the login user with the problem user in the users group?
What is the login user you created which works properly?

**Comment by nls1729** [comment]
Do you have /usr/bin/dconf-editor installed?
If not are you familiar with /usr/bin/gsettings?

**Comment by Kerrung** [comment]
@nls1729 'user" is the problem user and it is in the users group, not in the administrator/root group.
Previously, I created a user named "test" to test this release there, but I already checked everything there and everything is working fine so I already deleted this user along with ~ /.
Should I create a "test" user again? 
dconf-editor was not installed, but I just installed it at your request.

**Comment by nls1729** [comment]
Please do the following:

$ ls -l /home/user/.config/dconf/user       
Note the time.

Log out then log in.

$ ls -l /home/user/.config/dconf/user       
Note the time.

The time should be different indicating the user file was updated when you login.

Do you have other gnome shell extensions installed?

If you do try changing a preference setting on one of them and verify if the setting is
retained or not when you log out and login.

The key to the problem appears to be the failure of the user file to be updated.

You tested with a different user and the preference change was retained between logins.

It appears to be related to only the login user.  I also noticed the user file is large (43956).

The settings for a gnome shell session consist of two sources.  One is a group of files compiled from gsettings schema files and are system wide and affect all users.
Each user has ~/.config/dconf/user for settings in effect for only the user's session.  Extension preferences and many other things like application favorites in the overview are stored in the user file.

Try adding a favorite in the applications overview and logout and login and see if it is retained.

When you you upgraded to 3.30 were you logged in as user?

The journal may have some error messages that could help.

sudo journalctl --no-pager | grep /home/user/.config/dconf/user > /tmp/log.txt

Look at /tmp/log.txt and see if any of the messages indicate some error processing the file.

Do you have a backup of your home directory before the update?

**Comment by nls1729** [comment]
I tested several weeks ago using an early fedora test image.  When I tested today using the official fedora 29 beta 1.5 I found the bug you describe.  I have tracked down the changes in the latest GS3.30 which causes the problem.  I should be able to fix it this weekend.   I should have waited until I had a real beta to test with.  If the fix is not too complicated I will post a file here  you can use until the fix is available at the extension website.

**Comment by nls1729** [comment]
Since you are using Arch it would help if you could attach the extension.js file from your system on a comment here.

**Comment by nls1729** [comment]
The file is in   ~/.local/share/gnome-shell/extensions/activities-config@nls1729  .

**Comment by Kerrung** [comment]
[activities-config@nls1729.zip](https://github.com/nls1729/acme-code/files/2453428/activities-config.nls1729.zip)

**Comment by nls1729** [comment]
Got the zip.  I should have the fix done this evening.  I will post it here by tomorrow AM.

**Comment by Kerrung** [comment]
Thank you

**Comment by nls1729** [comment]
@Kerrung

Please replace the file 
~/.local/share/gnome-shell/extensions/activities-config@nls1729/extension.js
with the file extension.js in the attached zip file.

After replacement please verify “48803 Oct  6 18:32” with
$ ls -l ~/.local/share/gnome-shell/extensions/activities-config@nls1729/extension.js

Let me know how it goes..

[extension.js.zip](https://github.com/nls1729/acme-code/files/2453474/extension.js.zip)

**Comment by nls1729** [comment]
I am sure you know but just to be sure you must logout and login to complete the fix.

**Comment by Kerrung** [comment]
![screenshot from 2018-10-07 12-27-59](https://user-images.githubusercontent.com/36989404/46579494-7b408d80-ca2c-11e8-91ab-b10e38f62945.png)

**Comment by nls1729** [comment]
Please see attached.

[Issue.txt](https://github.com/nls1729/acme-code/files/2454011/Issue.txt)

**Comment by nls1729** [comment]
Are you using a theme different from the default?

**Comment by nls1729** [comment]
If you are not using the default theme the Override Shell Theme button in the preferences must be set to On for the Show Overview to work.

**Comment by Kerrung** [comment]
![screenshot from 2018-10-09 23-32-56](https://user-images.githubusercontent.com/36989404/46690436-b94fd400-cc1b-11e8-855e-8ac74d98e696.png)
![screenshot from 2018-10-09 23-31-56](https://user-images.githubusercontent.com/36989404/46690437-b94fd400-cc1b-11e8-8901-25fd9096831e.png)

**Comment by nls1729** [comment]
Something mangled my previous comment.

After looking at all the comments again based on the following:
You created a different user and found that the extension worked as it should.
Since the extension does not work properly under your user it must be something about your user setup.
You have a number of extensions enabled.
Extensions can interfere with each other.
Themes can interfere with extensions.

Insure an untouched AUR version of the Activities Configurator is installed in /usr/share/gnome-shell/extensions. There should be no Activities Configurator in /home/bogwan/home/user/.local/share/gnome-shell/extensions.

Try enabling Conflict Detection and reboot and test to determine if the Activities Configurator is operating properly.

If not before you continue at step 2, please add a user. Verify the extension still works properly with a different user. I want to be sure no updates have changed anything since we started looking at this problem.

2.  Disable all extensions except the Activities Configurator.
3.  Reboot your system.
4.  Test to determine if the Activities Configurator is operating properly.
5.  If is OK go to 6. If not OK go to step 7.
6.  Enable a disabled extension (one at a time). Logout and login. Test. Repeating this step until you find the offending extension or you run out of disabled extensions. If you find an offender stop and let me know which extension is the problem. If not go to step 7.
7. Give me the bad news.

**Comment by Kerrung** [comment]
@nls1729 I confirm that this bug is completely fixed using the latest master. Thank you so much for your great work!
