### ISSUE TITLE
Panel is transparent on half tile

### ISSUE THREAD

**Issue by Mipronimo** [nls1729/acme-code#47]
Hi again,
if I have to tile windows, it is like one is maximized, but the panel is transparent.
Is it possible to make it not transparent, if a window is in tile mode?

Thanks for your help.
![bildschirmfoto von 2018-12-11 12-53-40](https://user-images.githubusercontent.com/35998229/49799152-7b1e8000-fd44-11e8-9217-e590929aee11.png)

**Comment by nls1729** [comment]
@Mipronimo 
I have some test code that seems to work.  The code is too ugly for polite society.  I will clean it up this weekend.  I will get you a zip file to test in a few days.  Thanks for this issue.  The solution turned out to be simple but required a lot of digging through the shell's code.

**Comment by nls1729** [comment]
@Mipronimo 
From extension README.txt
... Tile Maximize Effect.  When tiling windows in native Gnome Shell two windows on the primary monitor will be adjacent to the panel.  If the panel has transparency applied the look is not good.  The Tile Maximize Effect applies the Window Maximize Effect of Opaque Background Color or Black Opaque Background to the panel depending on option selected.  The new option to turn the Tile Maximized Effect Off in the preferences is provided in case of a conflict with an installed tiling extension. ...

I was assigned, 1965-1969, to Lindsey Air Station (now known as Europaviertel) in Wiesbaden.  After almost fifty years any German I could speak then has escaped me.  From Google Translate "Tile Maximized Effect Off" is "Kachel maximiert Effekt aus".  If Tile Maximized Effect Off is checked the effect is disabled.  If you can provide a better translation I would use it in the extension.

Please test using the attached zip file and let me know what you think.

[activities-config@nls1729.zip](https://github.com/nls1729/acme-code/files/2683107/activities-config.nls1729.zip)


Thanks

**Comment by Mipronimo** [comment]
Thanks for your reply.
Currently it is a bit better, but still not done perfectly. If you move the window as a tile on one side, the panel is transparent. If you move it on the other side, it is not transparent. So the first time is transparent, after moving, it is not.
I don't know, if you know, what I meen. :D
Greetings
Micha

**Comment by nls1729** [comment]
I see what you see.

**Comment by nls1729** [comment]
@Mipronimo 
Season's greetings. 
Norman

**Comment by nls1729** [comment]
I found a case where the effect did not work properly.  The attached zip fixes it.  I have uploaded it to the extension website for review.

[activities-config@nls1729.zip](https://github.com/nls1729/acme-code/files/2733047/activities-config.nls1729.zip)

**Comment by Mipronimo** [comment]
Sorry, I didn't tested it yet.

> [activities-config@nls1729.zip](https://github.com/nls1729/acme-code/files/2733047/activities-config.nls1729.zip)
This one is not working for half tiles.
In fullscreen it is working fine.

Greetings
Micha

**Comment by nls1729** [comment]
I have not forgotten this issue.  My time is occupied with taking  care of a sick friend.  Hopefully I will have free time soon.

**Comment by Mipronimo** [comment]
@nls1729 no problem. I can wait (:

**Comment by nls1729** [comment]
@Mipronimo 

I hope I have it right this time.

I have tested with both single and all dual monitor configurations and it appears to now work as you requested.  Please try the attached zip file and let me know how it goes. 

[activities-config@nls1729.zip](https://github.com/nls1729/acme-code/files/2770846/activities-config%40nls1729.zip)

**Comment by Mipronimo** [comment]
@nls1729 lgtm.
Nice work! Thanks a lot.

**Comment by alperenkaplan** [comment]
> @Mipronimo
> 
> I hope I have it right this time.
> 
> I have tested with both single and all dual monitor configurations and it appears to now work as you requested. Please try the attached zip file and let me know how it goes.
> 
> [activities-config@nls1729.zip](https://github.com/nls1729/acme-code/files/2770846/activities-config%40nls1729.zip)

I have tried the attached zip but I still have the issue. I am on Pop OS 20.04, shell version 3.36

**Comment by nls1729** [comment]
Please install version 84 for Gnome Shell 3.36 at:

https://extensions.gnome.org/extension/358/activities-configurator/

Let me know if it works properly for you.

**Comment by nls1729** [comment]
@alperenkaplan 

See my previous comment for issue 47 which I reopened.

**Comment by nls1729** [comment]
Tested with Pop OS 20.04 with current updates and extension version 86 this morning.  Test OK.
