### ISSUE TITLE
Enable hot corner only for drag'n drop

### ISSUE THREAD

**Issue by Jehan** [nls1729/acme-code#5]
Hello,

I don't like the GNOME hot corner, so I disable it with the Activities Configurator extension.
Yet there is one case where I like it: when I drag'n drop a file to another application (which is not necessarily visible on my screen), for instance to drop a subtitle file over a running video player.

For this, I can drag my file over the hot corner which would display activities and workspaces, and still dragging, I can go over the right window.

Would it be possible to have an additional configuration when I disable the hot corner, saying basically "except for drag'n drop"?
This would be awesome. Thanks.

**Comment by nls1729** [comment]
Your suggestion is interesting.  I setup the following test to better understand what you want to accomplish.

1. Disabled hot corner.
2. Opened gedit and placed it in workspace 4.
3. I selected workspace 1 and opened nautilus.
4. I dragged a text file from nautilus to the hot corner.
5. I pressed the Super Key (aka the left Windows key) to open the overview.
6. I dragged the text file to workspace 4 and gedit became the active window and I dropped the file.
7. The text from the file was entered into gedit.

This seems to accomplish what you want to do with a keypress of the Suoer Key with the dragged object positioned in the (disabled) hot corner.

Does this approach satisfy your need?

**Comment by Jehan** [comment]
This approach does *sometimes* satisfy my needs, and this is already what I do these times. Actually using alt-tab, you would even have easier steps, since you don't have to drag the text to the hot corner (step 4). Just starting the drag and alt-tabing until you find your target application is enough. [Note: actually I really wonder why you would have to drag to the hot corner when you use the Super key method. I'm thinking this behavior should also be revised!]
These are my usual "work times", on a desk, with both hands on the keyboard most of the times anyway.

But there are other times when a cursor/mouse only approach is desired. Often my "lazy times", when I am watching a movie on my couch, with a beer in a hand, and the other hand on the laptop touchpad trying to drag and drop a file from my file browser into the video player. These times, I would really like to have an easy way "cursor-only" to drag from one app and drop to another.

GNOME 3 proposes this by default, but disabling the hot corner breaks it. I'd like a middle-ground if possible, with hot corner disabled but enabled only when dnd is in progress.

**Comment by nls1729** [comment]
It becomes a problem to add new features for older versions.  With the latest changes to the shell I add new features for the latest two versions 3.14 and 3.16.  I looked at the code and think it MAY be
possible to get it working to suit your needs.

What version of Gnome Shell do you have?

**Comment by Jehan** [comment]
GNOME-shell 3.16.3-1.fc22 (official Fedora build). So I guess it should be good. :-)
Thanks!

**Comment by nls1729** [comment]
François M.:
Jehan:

I have updated the Activities Configurator for GS 3.14 and 3.16 with the following:

Added code to be touch screen friendly. I can't test it but looking at the existing Shell's code I believe it will work.

Added the option to not display the icon for the currently focused application in the Application Menu Button on the left of the panel.

Changed the behavior of the hot corner when it is disabled. Dragging an item into the hot corner will display the overview and continue the drag. This is the default behavior for the hot corner when it is enabled.

I have not uploaded the extension for review yet.

If you would like to test for me please send me an email via the email link at:
https://nls1729.github.io

I will send you a zip file of the extension which can be installed with the Tweak Tool.

Thanks,
Norman

**Comment by Jehan** [comment]
Hi,

I sent an email 4 days ago (since I'd be happy to test) but had no answer. Have you seen it? :-)
Thanks!

Jehan

**Comment by nls1729** [comment]
I did not get your email.  I tested the email link at https://nls1729.github.io a couple of minutes ago and it is worked OK.  Please try again nls1729@gmail.com

**Comment by nls1729** [comment]
I did not get your email.  I tested the email link at 
https://nls1729.github.io a couple of minutes ago and it is worked OK. 
 Please try again nls1729@gmail.com

**Comment by Jehan** [comment]
I sent again. If not received again, it is maybe in your spam folder?

**Comment by nls1729** [comment]
You should get my reply and zip file shortly.
Thanks...

**Comment by Jehan** [comment]
> You should get my reply and zip file shortly.

Have you sent it? Because if so, there is definitely some curse against us communicating! I received nothing yet.

**Comment by nls1729** [comment]
I replied Friday. The Reply-to: in your email was jehan@gimp.org.
I just now replied to the Reply-to: of jehan@gimp.org and cc'ed the From: of jehan@girinstud.io
If you don't receive it within a couple of hours let me know an I'll try to find another way to get it to you.
I am cursed in many ways but never befored by the email gods.

**Comment by nls1729** [comment]
I updated the comments.  I too don't like evil bots.

**Comment by Jehan** [comment]
Works great! This is awesome. :-)

P.S.: thanks for editing the comment. You should also update your comment from 2 days ago where you wrote down your own email address.

**Comment by nls1729** [comment]
I am closing this issue.  Thanks for help.
