### ISSUE TITLE
GNOME 3.32 support?

### ISSUE THREAD

**Issue by Kerrung** [nls1729/acme-code#50]
Hi! Thank you for your work!
What about GNOME 3.32 support?

**Comment by nls1729** [comment]
I will update after I test with  Fedora 30 beta.  It will be by the end of March or early April.   I have wasted a lot of time  in the past trying to test with the Gnome Shell too early following its release.  A Fedora  beta seems to be the best bet to get a good test of a new shell release.   No extensions are being reviewed on the extension website < https://extensions.gnome.org/review/ > .  It appears no review has been done in the past two months or more.  I will comment here when I have updated the repo .  I have no idea when  extensions.gnome.org will be updated with an "official" version of the extension.  The original ground rule for extensions was to not use an extension that had not been reviewed and made available on the ego website.  I agree with the rule and will not provide an extension to the general public without review by Gnome.  If anyone reports a bug to me and agrees to test to determine if the bug has been cleared I will provide them a zipfile.

**Comment by Kerrung** [comment]
Yes, I want to test it.
Why you don't want to test it now on Arch Linux just now? So you no need to wait so long time.

**Comment by rockon999** [comment]
I submitted #51 to fix the issues on 3.32

**Comment by nls1729** [comment]
@rockon999  Thanks for your merge request. 

@Kerrung
I will make a few housekeeping changes and update the repo.   rockon999 has fixed the extension for 3.32.  You can clone the repo  after I make a few housekeeping changes.  I will comment here to let you know when the changes are made.  There is a Makefile for Activities Configurator in the activities-config directory to create a zip-file.

**Comment by nls1729** [comment]
@Kerrung 
I suggest you do the following to test the extension:
1. Got to the nls1729/acme-code on github.
2. Click on "Clone or Download"
3. Click on "Download Zip" 
(Much smaller download than Clone)
4. Unzip the zip file acme-code-master.zip
5. Change directory to acme-code-master/activities-config on a terminal window.
6. $ make zip-file
You can install the zip-file and test.  You can verify that you have installed
the version supporting GS 3.32 by looking at the  Activities Configurator
preferences.

Let me know how it goes...

**Comment by balvik** [comment]
I'm afraid it still doesn't work. The PR from @rockon999 seems to apply to one of your other extensions. The only change in the last commits for activities-config were to bump the version to 3.32. I downloaded your last commit, make zip-filed it, copied it to the extension director, confirmed in the extension setting I was on the latest version (v72) and tried it. Does nothing. Extension seems to load fine, no errors, the setting window looks fine. It just doesn't do anything, doesn't change the icon or text of the activities button, nor does it seem to affect the top bar in any was at all.

**Comment by Kerrung** [comment]
@nls1729 now with 7ef2b63 the extension runs correctly on GNOME 3.32, but it does nothing.

**Comment by wolfgangwuerfl** [comment]
Same for me, runs correctly but seems to does nothing

**Comment by nls1729** [comment]
@balvik 
The top two commits were my updates to the updates to README.txt, metadata.json and prefs.js.
The metadata.json was changed to reflect GS 3.32.  The Makefile for the zipfile places a sha256sum in the  README.txt and the pref.js is updated with the supported GS versions and extension version.
The third previous commit  85f7edf is the merge of rockon999's pull request. 

@Kerrung @rockon999 @balvik  @wolfgangwuerfl 
Thanks to all for your comments.  I have downloaded last night build of pre-release Fedora 30 with GS 3.32 to set up a test system to find the problem with the extension.

**Comment by nls1729** [comment]
@balvik 
I was confused and now I am embarrassed.   rockon999's merge request did update the  extension-reloader and not activities-config.  As they say an assumption and not checking all the details closely can make an ass out of one's self.  For what it is worth I now have a working pre-release Fedora 30 with GS 3.32 test system.  Thanks.   If I had read your comment closely and checked all the details of the merge request I would not have wasted your time with the previous comment.

**Comment by alberto2000** [comment]
Any update? Also for me, seems to run correctly but does nothing.

**Comment by balvik** [comment]
@nls1729 That's quite alright, I'm just grateful that there's a community of people such as yourself who make these useful extensions, without which gnome-shell would be barely usable.

**Comment by nls1729** [comment]
The Activities Configurator has some serious problems with Gnome Shell 3.32. I hope I can find a workaround for all the things that are broken.  I have it displaying plain text on the panel.  That's a start.  I don't have a lot of free time to work on it so it may take a while.

**Comment by alberto2000** [comment]
@nls1729 is there any way i could help? I've never written any gnome extensions but i think if you gave me a short intro on how it's built and where the current issues are i could go on from there

**Comment by nls1729** [comment]
@alberto2000
Thanks for your offer of help.   Gnome Shell extensions are monkey patches to the shell code.   You must study the shell's code to understand how a new release breaks your code.  I had good luck today and gained a good understanding of what needed to be done.   The main problem was  the new code changed a javascript class to a GObject class.  I found workarounds today to handle it.  I am testing now and found it to be less of a problem than I first thought.  In a day or two I will be able to have it fixed.  Again thanks for your offer.

**Comment by nls1729** [comment]
@Kerrung 
I have updated the repo.  I think I have got all the features working properly.  Please download a zip and give it a good workout.  Let me know how it goes.

**Comment by Kerrung** [comment]
@nls1729 I just tried your extension, it seems like works perfect! Thank you very much!
If I will find some any other bugs, I will open separate bug reports, but the main issue is solved, I think.
So, I close it.

**Comment by nls1729** [comment]
Activities Configurator version 73 for GS 3.32 is available at the Gnome extension website, please update to the official version:
https://extensions.gnome.org/extension/358/activities-configurator/
