### ISSUE TITLE
Need you my help with Russian language translate?

### ISSUE THREAD

**Issue by Kerrung** [nls1729/acme-code#53]
@nls1729 Thank you very much with the GNOME 3.32 rebase! https://github.com/nls1729/acme-code/issues/50
So, I feel I should help you too. 
Therefore, I offer you my help in translating the Activities Configurator settings into my native Russian language.
Need you my help?
![Screenshot from 2019-03-22 03-04-30](https://user-images.githubusercontent.com/36989404/54787967-48432c80-4c4f-11e9-8832-19808d85a32a.png)

[the SELECT button] [ВЫБОР]         Выбор значка
Масштабирование значка
Скрыть значок
Отступ значка
[the APPLY button] [ПРИМЕНИТЬ]        Новый текст     [Обзор]
Скрыть текст
Отступ текста
Удалить кнопку "Обзор"
Чувствительность горячего угла
Отключить горячий угол
Скрыть закругления углов панели
Скрыть кнопку меню приложений
Игнорировать тему GNOME Shell
Переключаться в "Обзор" если нет запущенных приложений
Задать цвет панели
Прозрачность панели
Цвет тени панели
Прозрачность
Толщина панели
Область размытия
Область распространения
                                                               | Панель - Без эффекта
Эффект при развёрнутом на весь экран окне | Непрозрачная панель | Отключить разворачивание окон на весь экран при вдавливании окон в верхний край экрана
                                            | Чёрная непрозрачная панель

Переместить кнопку "Обзор" вправо
Включить предотвращение конфликтов с другими расширениями
[СБРОС] Вернуться к настройкам по умолчанию
[ПРОЧТИ МЕНЯ] Описание этого расширения

**Comment by Kerrung** [comment]
README (ПРОЧТИ МЕНЯ)

Значок на кнопке "Обзор" можно выбрать с помощью кнопки "Выбор значка". Расстояние между значками на панели регулируется с помощью шкалы отступов. Значок можно удалить с панели с помощью переключателя "Скрыть значок".

Текст на кнопке "Обзор" можно изменить, введя "Новый текст" и нажав кнопку "ПРИМЕНИТЬ". Отступ от текста на панели регулируется с помощью шкалы отступов текста. Текст можно удалить с панели с помощью переключателя "Скрыть текст".

Отступ от текста и значка выполняется по горизонтали слева и справа и измеряется в пикселях.

Кнопка "Обзор" может быть удалена с помощью переключателя «Удалить "Обзор"».

Чувствительность горячего угла регулируется шкалой порогов горячего угла. Увеличивая это значение, чувствительность срабатывания горячего угла уменьшается, уменьшая шансы нежелательного срабатывания горячего угла при его случайном задевании. Переключение в "Обзор", используя горячий угол, отключается с помощью переключателя "Отключить горячий угол".

Если горячий угол отключен, обзор можно переключать нажатием на клавиатуре левой клавишей SUPER (ака "Windows").

Цвет панели может выглядеть более эстетично без черного фона панели. Цвет и прозрачность панели можно настроить с помощью кнопки "Задать цвет панели" и шкалы прозрачности панели (0–100%). По умолчанию 0, прозрачность отсутствует или непрозрачна, а 100 полностью прозрачна. Для этой функции требуется цвет обоев рабочего стола, который контрастирует с иконками и текстом, отображаемыми на панели.

Конфликты с другими активированными расширениями могут быть обнаружены с помощью переключателя "Включить предотвращение конфликтов с другими расширениями". Это расширение по умолчанию предпочитает самый левый угол панели. Любое другое расширение, которое встраивается в самый левый угол панели, считается конфликтующим с этим расширением. Это расширение пытается избежать конфликтов, задерживая его активацию во время запуска оболочки. Задержка, кажется, разрешает большинство конфликтов, позволяя расширениям функционировать нормально. Расширения, которые дублируют функции этого расширения, могут повлиять на это расширение или быть затронуты, когда они оба включены одновременно. Попробуйте разные настройки для конфликтующих расширений, чтобы избежать конфликтов. Обнаружение конфликтов по умолчанию отключено. Включите его только если у вас возникли проблемы. Когда обнаружение конфликтов включено, обнаруженные конфликты обычно автоматически разрешаются. Если конфликт обнаружен, это расширение восстановит свое предпочтительное положение на панели. Если другое расширение продолжает создавать конфликт, это расширение отключит себя, чтобы избежать состояния гонки и уведомить об этом пользователя. Пользователь может отключить обнаружение конфликтов, если допустимо, чтобы это расширение не находилось в его предпочтительном положении. Конфликт можно разрешить, отключив конфликтующее расширение или это расширение и перезапустив сеанс.

Настройки этого расширения сбрасываются до значений по умолчанию с помощью кнопки "СБРОС".

Кнопка "ПРОЧТИ МЕНЯ" предназначена для описания этого расширения и отображает этот файл.

Нажатие правой кнопкой мыши на значок или текст кнопка "Обзор" запускает настройки уже установленных у вас расширений GNOME Shell.

**Comment by nls1729** [comment]
I will need your help.

To do translations you must associate the original text to the translated text. If you will serve as the translator, I will provide you a .pot (Portable Object Template). This file will be named message.pot.  I will create it using the xgettext program.  xgettext will extract the original text strings from the extension source files which require translation. The .pot file entries look like the following:

#: extension.js:46
msgid "Conflict Detected:"
msgstr ""

#: extension.js:46  identifies the name of the source file and the number of the line containing the original text.
msgid               is the original text "Conflict Detected:"
msgstr ""           is where translated text is entered.

If the translated text is very long you simply add the extra text below the msgstr line.
 
Example:

#: extension.js:46
msgid "Conflict Detected:"
msgstr "Translated text goes here. "
"This is where more text goes when the first line is very long."
" This is more text.  You can have as many lines as you need."

I need to create a new .pot file. I will post it post it here soon.

**Comment by nls1729** [comment]
@Kerrung 
The following zip file contains message.pot.  You can click it to download.  When you finish entering the translated text it will become a .po file (Portable Object).  Rename message.pot to ru.po.  Make a zip file of ru.po and attach  it to a comment here.  I will update the extension by adding it to  the po directory and update the repo.  You can then download a new zip file from the repo.   When the extension's Makefile is processed a ru.mo (Machine Object) will be created.  Make a new activities-config@nls1729.zip and install it.  The extension should  then display Russian.

[message.zip](https://github.com/nls1729/acme-code/files/2999240/message.zip)

If you are interested, GNU gettext utilities covers all aspects of translations.  It really provides a lot of information.  It is a good reference but I have never found the need to read all of it.
< https://www.gnu.org/software/gettext/manual/gettext.html >

**Comment by Kerrung** [comment]
[ru.zip](https://github.com/nls1729/acme-code/files/2999375/ru.zip)
@nls1729  I translated about a third, but before I continue, I would like you to look at it and confirm to me that I am doing everything right there.

**Comment by nls1729** [comment]
I found a problem that prevented all the text that needed translation from being included in the .pot file.  I will not be able to work on this problem for a few days.  I  should be back by Tuesday of next week.

**Comment by nls1729** [comment]
@Kerrung 

I created a new ru.po file named ru_redo.po  The file has all the msgid entries that need translating. I took the ru.po file you asked me to look at and used the data you had entered and updated the ru_redo.po file. Please check and make sure I did not make any errors.  You can update ru_redo.po  and we should be able to finish the translations.  My plans have changed.  I will be away Monday and Tuesday.

Zipped ru_redo.po:  
[ru_redo.zip](https://github.com/nls1729/acme-code/files/2999864/ru_redo.zip)

**Comment by nls1729** [comment]
@Kerrung 
This file may help explain the way the file needs to be updated.
[ru.txt](https://github.com/nls1729/acme-code/files/2999866/ru.txt)
