### ISSUE TITLE
Not working on 3.32

### ISSUE THREAD

**Issue by raczkerry** [nls1729/acme-code#54]
Hi,
I wanted to test your last version of Activities configurator but it doesn't work.
When I try to open the settings I get this error :

The settings of extension activities-config@nls1729 had an error:
```
GLib.FileError: Failed to open file “/home/kerry/.local/share/gnome-shell/extensions/activities-config@nls1729/schemas/gschemas.compiled”: open() failed: No such file or directory
```

Stack trace:
```
getSettings@/home/kerry/.local/share/gnome-shell/extensions/activities-config@nls1729/convenience.js:80:24
_init@/home/kerry/.local/share/gnome-shell/extensions/activities-config@nls1729/prefs.js:68:23
buildPrefsWidget@/home/kerry/.local/share/gnome-shell/extensions/activities-config@nls1729/prefs.js:635:18
_selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:75:22
_onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:320:17
main@resource:///org/gnome/shell/extensionPrefs/main.js:635:5
@<main>:1:43
```
`

**Comment by nls1729** [comment]
It appears you downloaded the zip file for the nls1729/acme-code repository or you used git to clone the repository.  I think you then copied the files from the activities-config directory to  .local/share/gnome-shell/extensions/activities-config@nls1729 in your home directory.  That won't work.

You must use the make program to create a zip-file,  activities-config@nls1729.zip .
The following will get you the zip file you need.  You can skip anything step you have already done.
 
1. Go to the nls1729/acme-code on github.
2. Click on "Clone or Download"
3. Click on "Download Zip"
    (Much smaller download than Clone)
4. Unzip the zip file acme-code-master.zip
5. Change directory to acme-code-master/activities-config on a terminal window.
6.  $ make zip-file
7. [Remove , rename or move] activities-config@nls1729 directory  from ~/.local/share/gnome-shell/extensions .
8. [Move or copy] activities-config@nls1729.zip to ~/.local/share/gnome-shell/extensions .
9. With the Files application go to ~/.local/share/gnome-shell/extensions  and  Select
activities-config@nls1729.zip then right click, then select  Extract Here.
10. Log out, log in and all should be OK.

Let know how it goes.  I won't close this issue until I know you are happy :).

**Comment by raczkerry** [comment]
Well, I'm happy!

Thank you for your kindness and of course for this great extension.

**Comment by nls1729** [comment]
Activities Configurator version 73  for GS 3.32 is available at the Gnome extension website, please update to the official version:
https://extensions.gnome.org/extension/358/activities-configurator/
