### ISSUE TITLE
Do Not Disturb Button Extension Gnome 3.32

### ISSUE THREAD

**Issue by scan09** [nls1729/acme-code#55]
login leaves this:
https://i.imgur.com/JeAkTIw.png

**Comment by nls1729** [comment]
It looks like it is working as it should.  Read the README.txt file Description of the Busy State Timeout Feature.

The Once Radio Button is used to select a one time timeout. When the
Enable Check Box is checked and the Once Radio Button is selected a
timeout starts when the extension's busy state is set. When the one
time timeout expires the Busy State Timeout Feature is disabled.
A notification is sent, "Timeout Once Busy State Timeout expired.
Timeout disabled". The Busy State Timeout Feature will not start
a new one time timeout until the Enable Check Box preference is
checked to re-enable the Busy State Timeout Feature.  If during the
duration of a one time timeout the Gnome Session is ended at the next
session start the Busy State Timeout Feature will be disabled and a
notification is displayed, "Timeout Once Found at Session Start Busy
Timeout is disabled".  If there are unviewed notifications in the
in the queue notifications may not be displayed but will be added
to the queue.

**Comment by nls1729** [comment]
Set the Always radio button to disable the Once timeout warning at session start.

**Comment by nls1729** [comment]
I changed the code to only show the warning at the next session start. If you want a quick fix 
find line:
Notify.notify(_("Timeout Once Found at Session Start"),_("Busy State Timeout is disabled.")); 
in file extension.js . 
After that line add:
this._settings.set_boolean('time-out-always', true);

**Comment by scan09** [comment]
Esta es la configuración:
https://i.imgur.com/1rBJe9i.png

En cada inicio aparece esto:
https://i.imgur.com/JeAkTIw.png

**Comment by scan09** [comment]
> I changed the code to only show the warning at the next session start. If you want a quick fix
> find line:
> Notify.notify(_("Timeout Once Found at Session Start"),_("Busy State Timeout is disabled."));
> in file extension.js .
> After that line add:
> this._settings.set_boolean('time-out-always', true);

I'm going to try

**Comment by scan09** [comment]
> > I changed the code to only show the warning at the next session start. If you want a quick fix
> > find line:
> > Notify.notify(_("Timeout Once Found at Session Start"),_("Busy State Timeout is disabled."));
> > in file extension.js .
> > After that line add:
> > this._settings.set_boolean('time-out-always', true);
> 
> I'm going to try

it's works

**Comment by nls1729** [comment]
I am working on adding the option to mute the sound when the busy state is active.  I also will remove the message Timeout Once Found at Session  - Start Busy State Timeout is disabled.  I think the message is not necessary.   Thanks for reporting this issue.

**Comment by nls1729** [comment]
@scan09 

Version 31 of the extension is now available at: 
<https://extensions.gnome.org/extension/964/do-not-disturb-button/ >

The message has been removed.  Thanks for reporting this issue.
