### ISSUE TITLE
gnome-shell 3.32.2 - using a lot of RAM after awhile

### ISSUE THREAD

**Issue by brunobottazzini** [nls1729/acme-code#59]
Hi, this extension is amazing! 

But after I updated from Fedora 29 to 30 and also updated gnome-shell to version 3.32.2 I noticed a memory leak on it.

After talking to some people it was advised to turn the extensions off and so I did it. After investigating which extension was causing the trouble. Unfortunately, it was this one.

After 24 hours the gnome-shell was occupying 4.5gb of RAM and the memory leak goes on until the system stops responding.

**Comment by nls1729** [comment]
Which version of the extension is installed?

**Comment by brunobottazzini** [comment]
Hello,

Sorry I totally forgot to pass this information:

The version that was installed was: Version 74 GS 3.32

**Comment by nls1729** [comment]
@brunobottazzini 

Version 75 is available at the extension website (extensions.gnome.org).

I have questions:

How much ram and swap space is on your computer?

Did you do your upgrade with dnf or the Software GUI?

What tool did you use to monitor the memory usage?

When you did testing to determine which extension was at fault,
did you remove the extensions or simply disable them?

I am testing and have not been able see the memory usage you
reported.  From what you reported the problem was very easy
to observe.

Memory leaks are bad news.  I will continue to test.

Thanks,
Norman

**Comment by brunobottazzini** [comment]
@nls1729,

RAM: 16GB
SWAP: 7.64GB

- I think I haven't upgraded to the last version or at least I always used https://extensions.gnome.org/
- I removed (not disable) one by one until I noticed that the memory leak has stopped.
- I will upgrade to the last updated version and test it to see if now I can replicate the problem.

Maybe in my environment there is something that helps cause the problem.

**Comment by brunobottazzini** [comment]
@nls1729, 

Ok I reinstalled it from https://extensions.gnome.org/  
![Schermata da 2019-06-11 16-43-19](https://user-images.githubusercontent.com/4460234/59281739-0f23c280-8c68-11e9-91ca-7ce027506354.png)
![Schermata da 2019-06-11 16-43-28](https://user-images.githubusercontent.com/4460234/59281752-12b74980-8c68-11e9-9ed7-88cea055a725.png)

I run a test and using my pc for a day I noticed the memory leak . 

I let it for at least 8 hours running non stop off course. 


Difference from one hour to another
4.44 p.m
![Schermata da 2019-06-11 16-46-54](https://user-images.githubusercontent.com/4460234/59286968-04b9f680-8c71-11e9-8559-325fcb11ba8b.png)

5.45 p.m.
![Schermata da 2019-06-11 17-45-29](https://user-images.githubusercontent.com/4460234/59286858-ccb2b380-8c70-11e9-8fb0-8445ab4c9062.png)


It does not stop increasing. 

Unfortunately today I cannot let my computer on overnight to make it arrive on 4.5gb but you can see that 942mb is a lot.

**Comment by nls1729** [comment]
gdm is running gnome-shell.  Are you not logged into a shell session?   Are you logged in with ssh?
When gdm runs gnome-shell it has no extensions.   This is getting to be very strange.

**Comment by nls1729** [comment]
When you run your test are all the extensions in both ~/.local/share/gnome-shell/extensions and
/usr/share/gnome-shell/extensions removed with the exception of activies-config?

**Comment by brunobottazzini** [comment]
> gdm is running gnome-shell. Are you not logged into a shell session? Are you logged in with ssh?
> When gdm runs gnome-shell it has no extensions. This is getting to be very strange.

Strange... maybe because I am using Fedora and it is based on Wayland? It is my work computer I am not logging into this computer via SSH however I use a lot docker and ssh to another machines.

> When you run your test are all the extensions in both ~/.local/share/gnome-shell/extensions and
> /usr/share/gnome-shell/extensions removed with the exception of activies-config?

All my custom extensions are located ~/.local/share/gnome-shell/extensions and yes it has been removed.

**Comment by brunobottazzini** [comment]
So today i ran a test without the plugin and I took a screenshot at 9.55 a.m and another 5.00 p.m.

9.55 a.m.
![Schermata da 2019-06-12 09-55-13](https://user-images.githubusercontent.com/4460234/59362359-98ec9200-8d33-11e9-96e5-ec5c457a0c10.png)

5.00
p.m.
![Schermata da 2019-06-12 16-59-19](https://user-images.githubusercontent.com/4460234/59362383-a30e9080-8d33-11e9-9600-887816e8008e.png)

Not sure why this behavior happens as gdm. Since it does not use any extension as you said.

**Comment by nls1729** [comment]
From the above I assume you were logged into a gnome-shell session to take the screen shots.
If you were logged into your system it seems there is something very wrong.   From all the testing I have done during the past few days,  gdm only owns gnome-shell when no regular users are logged in.

Please see the attached text file.
[yarlogin.txt](https://github.com/nls1729/acme-code/files/3282539/yarlogin.txt)

Try rebooting your system and log in with a different user than your regular user.
If gdm does not own gnome-shell your home directory may have a problem.  If gdm does own gnome-shell your system is not working as it should.   

Let me know how it goes.

**Comment by brunobottazzini** [comment]
Hello,

I will make the test and inform you what happened :).

Either way it is my distro fault so I am closing the issue.

Thank you very much!!

**Comment by brunobottazzini** [comment]
I just recreate the user and reboot it and I cannot find the gdm gnome-shell so I think that this settles our problem.

Thank you once more.
