### ISSUE TITLE
Activities Configurator - Disable bar styling

### ISSUE THREAD

**Issue by wyqydsyq** [nls1729/acme-code#61]
The top bar styling feature of Activities Configurator conflicts with the similar functionality provided by `Dash to Panel` which arguably offers a better implementation, the nature of the conflict is that `Activities Configurator` seems to load after `Dash to Panel`, overriding the latter's custom gradient bar with the default styling from the enabled shell theme.

The bar styling feature needs an option to disable it entirely to avoid this conflict, or ideally it should just be removed since styling the top bar is entirely out of the scope of configuring the "Activities" menu.

I only want to use this extension to hide the Activities text and show an icon for the button instead without overriding the top bar styling from other extensions.

**Comment by nls1729** [comment]
The two extensions monkey patch the same shell code.   I suggest you not use the Activities Configurator.  "... ideally it should just be removed since styling the top bar is entirely out of the scope of configuring the "Activities" menu."  That's really funny.

**Comment by wyqydsyq** [comment]
Awesome that would be great, as replacing the Activities text with an icon (or emoji will suffice) is all I wanted to use this extension for. I imagine other people might like this too so rather than just sharing a zip it might be worth publishing to the GNOME Extensions portal, or if you don't want to go to the effort and are willing to share your source I'd be happy to publish and maintain it.

Thanks :)

**Comment by nls1729** [comment]
Thanks for for reply. I will be out of town for a day or two.  I will provide you the tools to publish and maintain the extension when I return.  I am happy for you to share the extension on extensions.gnome.org and maintain it.

**Comment by nls1729** [comment]
The following should be all you need.

Please see attached procedure:

[transfer-procedure.txt](https://github.com/nls1729/acme-code/files/3563619/transfer-procedure.txt)

You will need this file.

[transfer-repo.zip](https://github.com/nls1729/acme-code/files/3563614/transfer-repo.zip)

If anything doesn't work I am sure we can fix it.

I have also attached a zip file and the README.txt for gse-zip-tool referred to in the procedure.

[gse-zip-tool-master.zip](https://github.com/nls1729/acme-code/files/3563634/gse-zip-tool-master.zip)

[README.txt](https://github.com/nls1729/acme-code/files/3563635/README.txt)

Happy U.S. Labor Day,
Norman

**Comment by nls1729** [comment]
@wyqydsyq 

Hello,
For some unknown reason I took a look at the files in transfer-repo.zip.  I found an error.  It is a one line change that I have noted in the attached replacement for transfer-procedure.txt.  Please use the following  file instead of transfer-procedure.txt in the previous comment.  The updated procedure identifies the error and provides the needed correction.

[transfer-procedure.20190905.txt](https://github.com/nls1729/acme-code/files/3581148/transfer-procedure.20190905.txt)
