### ISSUE TITLE
3.34 Support

### ISSUE THREAD

**Issue by KUPOinyourWINDOW** [nls1729/acme-code#62]
Any chance you could get this up and running for 3.34 please?

It installed fine and I see the smiley face at the top left, but if I try to open the settings within gnome tweaks I get this:

`TypeError: Me.metadata['shell-version'] is undefined

Stack trace:
  _init@/home/reece/.local/share/gnome-shell/extensions/activities-config@nls1729/prefs.js:53:1
  buildPrefsWidget@/home/reece/.local/share/gnome-shell/extensions/activities-config@nls1729/prefs.js:626:18
  _showPrefs@resource:///org/gnome/shell/extensionPrefs/main.js:57:22
  _extensionsLoaded@resource:///org/gnome/shell/extensionPrefs/main.js:319:13
  _scanExtensions/<@resource:///org/gnome/shell/extensionPrefs/main.js:297:13
  asyncCallback@resource:///org/gnome/gjs/modules/overrides/Gio.js:132:13
  main@resource:///org/gnome/shell/extensionPrefs/main.js:702:5
  @<main>:1:43`

**Comment by nls1729** [comment]
It is already on my to-do list.  Hopefully I can get around to it in the next few days.

**Comment by nls1729** [comment]
@KUPOinyourWINDOW 
RE - GS 3.34 support.

I have attached instructions for getting a test version of the extension.  I believe I have gotten all the bugs out, but if you would test it a bit for me I would be grateful.

[Links.txt](https://github.com/nls1729/acme-code/files/3631440/Links.txt)

**Comment by KUPOinyourWINDOW** [comment]
Took me ages to figure out how to use gnome-extensions to install and enable the extension, simple drag and drop didn't work for some reason.

It all seems to be working fine, for example I have transparency set to 15, icon hidden and activities text padding set to 0 and all of the options have worked for me.

![Screenshot from 2019-09-20 06-49-51](https://user-images.githubusercontent.com/7698035/65302493-42cd8d00-db73-11e9-9d46-fa630d05af50.png)

**Comment by nls1729** [comment]
@KUPOinyourWINDOW 

I will upload version 76 to  extensions.gnome.org today.
When it is reviewed and available I will comment here and
close this issue.

Thanks for testing.

**Comment by KUPOinyourWINDOW** [comment]
Perfect, thanks for the fast support!

**Comment by nls1729** [comment]
@KUPOinyourWINDOW 

The version 76 of the Activities Configurator Extension passed review and is available .

**Comment by Kerrung** [comment]
> @KUPOinyourWINDOW
> 
> The version 76 of the Activities Configurator Extension passed review and is available .

Thank you, but I would like it to be added to this repository, I really need it.

**Comment by nls1729** [comment]
How would I add you  to this repository?

**Comment by Kerrung** [comment]
> How would I add you to this repository?

I believe that making changes to the code of this extension in this repository that adds support for GNOME 3.34 should be done in the same way as you have always done before in this repository all these years, when you made changes to the code of this to be compatible with new releases of GNOME extensions. But now, unfortunately, I do not see new commits here that add support for GNOME 3.34. Is now https://extensions.gnome.org/ the only and no alternative way to update this extension? I want to continue to install updates for this extension for myself, using this git repository as a source of updates, that is, in the same way as I always did before.

**Comment by nls1729** [comment]
@Kerrung 

Thanks for your comment and reply to my question.

Nothing has really changed.  I create a branch on my local repository.  I update the extension.  I test and often if someone has reported an issue I ask them to test.  I upload the extension to extensions.gnome.org.  When it is reviewed and accepted, I push the changes to the git repo. I often don't do the github repo push until a few days after the review is completed. I may be out of town when the review is completed.  I often don't push immediately because I am a very busy person.  The site extensions.gnome.org is the official source for gnome shell extensions.  I often don't update the documentation web pages at the link  https://nls1729.github.io/activities_config.html for several days after the code update of the github repo.  This stuff is open source.  I don't get paid to do it.  Doing what I get paid for takes priority over what I do in my free time.  With all that said, I try to satisfy folks who use my code so before I leave this Sunday morning at 6:55AM I pushed the GS3.34 Activities Configurator to github.

**Comment by Kerrung** [comment]
> @Kerrung
> 
> Thanks for your comment and reply to my question.
> 
> Nothing has really changed. I create a branch on my local repository. I update the extension. I test and often if someone has reported an issue I ask them to test. I upload the extension to extensions.gnome.org. When it is reviewed and accepted, I push the changes to the git repo. I often don't do the github repo push until a few days after the review is completed. I may be out of town when the review is completed. I often don't push immediately because I am a very busy person. The site extensions.gnome.org is the official source for gnome shell extensions. I often don't update the documentation web pages at the link https://nls1729.github.io/activities_config.html for several days after the code update of the github repo. This stuff is open source. I don't get paid to do it. Doing what I get paid for takes priority over what I do in my free time. With all that said, I try to satisfy folks who use my code so before I leave this Sunday morning at 6:55AM I pushed the GS3.34 Activities Configurator to github.

Thank you
