### ISSUE TITLE
With Fedora 31 (more recent Gnome version), it interferes with application keyboard use

### ISSUE THREAD

**Issue by lsatenstein** [nls1729/acme-code#64]
**Here are two examples.**
When active...
Using LibreOffice or Firefox, the following problems are 

**Control-S within LO is intercepted by Gnome,** Control-S should perform a save of the document.

**With Firefox and other,  Control + Scroll wheel** should change the main window presentation size (zoom/unzoom).

Disabling this extension reverts the functionality of the other applications.

**Comment by lsatenstein** [comment]
With Gnome 3.32, your application appears to work OK.

**Comment by nls1729** [comment]
I have Fedora 31 Beta with all available updates installed.  I tested the extension version 76 for GS 3.34.  LibreOffice and Firefox both work properly for the keyboard short cuts with the extension enabled.
