### ISSUE TITLE
Update github.io for your latest releases

### ISSUE THREAD

**Issue by terrycloth** [nls1729/acme-code#65]
This is a minor issue, but your github.io site was never updated for the Do Not Disturb Button v33 and v34 releases, or Activities Configurator v76.

You encourage people to download from the GNOME Shell Extensions website anyway, so this mostly an issue for me because Fedora release monitoring watches your github.io site, so I haven't been getting notifications to package the latest updates for your extensions.

**Comment by nls1729** [comment]
I will get to it sometime in the future.  My free time and then some is now spent with my wife who is hospitalized with a serious illness.

**Comment by nls1729** [comment]
I updated the  github.io site.  I will leave this issue open for a while in case I did not do all that I should.
Just curious, is the site monitored manually or by software?

**Comment by terrycloth** [comment]
Fedora uses the Anitya software service at [Release-Monitoring.org](https://release-monitoring.org/) to watch for updates. For each package on each participating Linux distro, Release Monitoring basically just uses a regular expression on the upstream release pages to find all the listed version numbers, and then compares with the list of versions that it already knows about. It then automatically generates notifications for packagers, like me.

**Comment by terrycloth** [comment]
Release Monitoring correctly detected the new versions of [Activities Configurator](https://release-monitoring.org/project/13774/) and [Do Not Disturb Button](https://release-monitoring.org/project/13766/), so I think you're good now. Thanks!
