### ISSUE TITLE
Close button on warning message doesn't work

### ISSUE THREAD

**Issue by mrzor** [nls1729/acme-code#66]
Greetings!

Got this message after upgrading to 19.10 - ![Screenshot from 2019-11-30 04-11-41](https://user-images.githubusercontent.com/54230/69894950-b33d1b00-1327-11ea-8f1a-b87f6e117434.png).

Successfully updated to v77 (which fixed configurator), but the message didnt go away. Had to restart Gnome Shell with `ALT-F2 r` twice to make it go.

Couldn't click close, or clicking close had no effect - not sure which.

I suspect that the 3840*2160 resolution with 200% scale is related.

Using 3.34.1+git20191024-1ubuntu1~19.10.1 as you probably guessed.

Thanks for all your good work on this extension :) It scratches more itches than I can count.

**Comment by nls1729** [comment]
I believe the problem you reported was corrected in update to Version 75 GS 3.32.
 
From "https://nls1729.github.io/activities_config.html" Latest Update link.

"User reported unable to close a message concerning missing hot corners. POP OS 19.04 is based on Ubuntu which has a patch applied to the shell which causes the missing hot corners. Gnome Shell 3.32 apparently does not allow a reactive St.Bin which was used to close the message. The St.Bin has been replaced with an St.Button to fix the problem."

If you were using a version earlier than 75, it would fail as you described.  The updated version was available shortly after 2019-05-25.

I will leave this issue open.  If you know for sure you were using version 75 or 76 let me know.  If I don't hear from you I will close this issue after thirty days.

**Comment by mrzor** [comment]
I'm quite sure I updated Activities Configurator at least once since June. The update notifications are quite hard to ignore! Unfortunately I wasn't able to find anything related to AS upgrades in the journal so I don't have proof. Would you know a way to be sure ?

**Comment by nls1729** [comment]
If you have a backup of your home directory created before you did the 19.10 upgrade,  the extension version of the Activities Configurator would be available in:
 ~/.local/share/gnome-shell/extensions/activities-config@nls1729/metadata.json
