### ISSUE TITLE
Enabling Panel Shadow Forces Panel Background Colour Change

### ISSUE THREAD

**Issue by fishears** [nls1729/acme-code#7]
Hi
With the new release, if I set any values for the Panel Shadow then it automatically applies the Panel Background colour from "Set Panel Background". This means it is impossible to use a theme's colour scheme while having a shadow enabled. Can you make "Set Panel Background" to have an on/off toggle to fix this?
Thank you

**Comment by fishears** [comment]
sorry, more on this, it seems that it is only when I increase Vertical Length to anything above 0 that this occurs

**Comment by nls1729** [comment]
I need a bit more information before I can address this issue.
What version of the extension do you have installed?
Where did you get the extension? (extensions.gnome.org, github, other)
Which theme are you using?
What linux distribution and version is installed?
As a workaround until I can hopefully fix the problem try the following:
1. Get the hex color code for the theme's panel background with gcolor2.
2. Set the extensions background color to the hex code from step 1.

Regards,
Norman

**Comment by fishears** [comment]
HI, sorry for the lack of detail.
I'm using the latest extension available at extensions.gnome.org.
Running Ubuntu Gnome 15.10 with Gnome Shell 3.18.2
The theme I first noticed the problem on is "Paper" from https://snwh.org/paper/ but the behaviour is the same for all other themes I've tried which have a non-black top bar.

Thanks for the workaround tip. Let me know if you need any more details from me.

**Comment by nls1729** [comment]
Hello:
I should have a new version ready in a day or two.  If you would like to test for me, I can email you a zip-file.   The zip is about 34K. I did not add a new option.  I determine if a user theme is present and allow the theme to override the extension.  It was a good problem to solve.  There is a mail link for me at  https://nls1729.github.io .

**Comment by nls1729** [comment]
I have been a bit busy lately.   Version 44 is available on the ego website.  It supports GS 3.16 3.18 and 3.20.  I am closing this issue.  If you have any problems please open a new one.

Regards,
Norman
