### ISSUE TITLE
Feature request - ability to reload enabled extensions

### ISSUE THREAD

**Issue by yuriw** [nls1729/acme-code#75]
Here is my use case.

I see on the top bar panel icons for chrome and hangouts after fresh system reboot and start.

However after the system (Ubuntu 20.04) was locked (Super-L) and then unlocked, those icon disappear.

Of cause, it can be due to many reasons.  My hope was that by reloading individual extensions (Dash to Panel is being one of them) it can help troubleshoot/fix the issue.

However, enabled individual extension can not be reloaded.
If that makes sense, pls consider

**Comment by nls1729** [comment]
You can't reload extensions without stopping and re-starting the Gnome Shell by logging out and then logging in.  An extension is a patch.  You can't un-patch without stopping and re-starting the running code.  You can't replace a fan belt with the motor running.
  
The following comment is from  extensions.gnome.org on the Dash to Dock page.  It may be related to your problem.
 
In Ubuntu version 20.04, disabling the Ubuntu Dock extension using the new Extensions App is needed, If not disabled both Docks will show, after a logout and some random moments (also noticed an increase in Resources usage).

**Comment by nls1729** [comment]
If you can do your testing using Xorg and Alt+F2 r before you reload,  I will have a version you can try by tomorrow.  I understand that Ubuntu 20.04 can be run  with Xorg instead of Wayland.

**Comment by blipk** [comment]
You can look at runDialog.js in the gs source for how the 'r' restart works on X11, or you can use this on Wayland: dbus-run-session -- gnome-shell --nested --wayland

I tried your extension and I don't get any menu pop-up on the latest Fedora 32.

**Comment by nls1729** [comment]
I have had a streak of bad luck.  My internet service was out for the past week.  I was in the middle of an update on my development system when the internet went out crashing my system.  One of the backup disk of  the system  failed.  It will take a few weeks to get back to semi-normal.  The city is re-surfacing the streets in my neighborhood.  They are removing  all the asphalt and then mixing a special cement in with the clay.  It is a long slow process.  I find myself trapped and can't drive out onto the street.  I had a version of the extension working on Fedora 32 just before my crash.  I hope I can recover it and not have to start from the beginning.  So it goes...

**Comment by nls1729** [comment]
@yuriw 
Version 12 of the Gnome Shell Extension Reloader is available.  It will reload enabled extensions but due to limitations of the Gnome Shell Extension system a session restart is required to complete the replacement of the code in memory.  Please look at the following link and take a look at the bug reports that are referenced at the bottom of the page.
Version 12 website:
https://nls1729.github.io/extension-reloader.html
Version 12 extension:   
https://extensions.gnome.org/extension/1137/gnome-shell-extension-reloader

**Comment by yuriw** [comment]
@nls1729 copy and thx ! Will take a look !

**Comment by nls1729** [comment]
No recent comments on this issue.  I assume  version 12 of the extension and using an Xorg session for testing  is satisfactory.
