### ISSUE TITLE
Dash to Panel Compatiablity (Activities Configurator)

### ISSUE THREAD

**Issue by PizzaLovingNerd** [nls1729/acme-code#78]
Hello, I am a distro dev trying to make a custom GNOME setup. I was trying to use Activities Configurator to give the activities button an overview icon similar to Windows 10

![image](https://user-images.githubusercontent.com/13041099/94348556-210ead80-fff2-11ea-9b2a-752052a3b510.png)

However the activities button doesn't show up on Dash to Panel when using Activities Configurator, even if the activities button is enabled in the Dash to Panel settings.

Before:
![image](https://user-images.githubusercontent.com/13041099/94348580-4996a780-fff2-11ea-8704-af3e649b3519.png)

After enabling Activities Configurator:
![image](https://user-images.githubusercontent.com/13041099/94348587-5a471d80-fff2-11ea-97fe-2560454acefc.png)

This extension would be amazing to use on Dash to Panel, so I hope you can help me with this.

Thanks
- PizzaLovingNerd

**Comment by nls1729** [comment]
I do not want the Activities Configurator to be associated with the Dash to Panel.  They are not compatible.
