### ISSUE TITLE
Extension reloader: Error message unreadable

### ISSUE THREAD

**Issue by piegamesde** [nls1729/acme-code#79]
![image](https://user-images.githubusercontent.com/14054505/97448493-000ee480-1931-11eb-9be0-b79b04d7acb0.png)

Thanks for the error message, I guess?

**Comment by nls1729** [comment]
@piegamesde 
"I guess?"  

The error message is complete.

The message indicates that the extension  CustomCorner did not load and  gives you the  first few  characters of the name of the extension's directory.   You need to look in the log to find the error details.  The following is an example where the log is provided by systemd.

[example.txt](https://github.com/nls1729/acme-code/files/5453888/example.txt)

Does this help you understand how to use the extension reloader?

**Comment by piegamesde** [comment]
Thank you for the explanation. I didn't realize that the error message was from the extension I was reloading, not from the reloader itself. Some improvement suggestions:

- Clicking on the error message should do something, e.g. pop up a dialog with the full error message or open the folder of the failed extension
- Maybe phrase the error message in a way that makes it more clear that the extension being reloaded has the error, not extension reloader itself.
- Compact the error message somewhat. I think "Error reloading 'CustomCorner': FOO" would be more readable and also show more of the rest of the string.

**Comment by nls1729** [comment]
@piegamesde  

Take a look at the following link and let me know if the update to the Gnome Shell Extension Reloader's web page satisfies your suggestions.   < https://nls1729.github.io/extension-reloader.html >
