### ISSUE TITLE
Activities Configurator 89 incompatible with GNOME 40

### ISSUE THREAD

**Issue by audreytoskin** [nls1729/acme-code#80]
I'm testing the upcoming GNOME 40 in a virtual machine of Rawhide (development branch of Fedora) x86_64. I'm using the RPM build of Activities Configurator v89.

Looking Glass shows no error messages for Activities Config (because the extension hasn't been enabled yet). But in the GNOME Extensions app, there's a red ⛔ warning icon, and the toggle switch to enable Activities Config is grayed out. If you click the gears icon to see Activities Config settings, you get a dialog that says "Something went wrong" and the following error message:

```
TypeError: noIconBox.pack_start is not a function

Stack trace:
  _init@/usr/share/gnome-shell/extensions/activities-config@nls1729/prefs.js:100:19
  buildPrefsWidget@/usr/share/gnome-shell/extensions/activities-config@nls1729/prefs.js:640:18
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by nls1729** [comment]
@audreytoskin

Activities Configurator, activities-config@nls1729 - Effective March 29, 2021 the extension is NOT MAINTAINED. I give my permission to anyone who may want to become the maintainer. I no not have the free time or energy necessary to maintain the extension.

I have posted the above notice on the extension website.

I do not usually post any personal information but I think you should get an explanation for my decision. I wrote my first code 55 years ago. I was not a child at the time. My age and recent changes in my personal situation have really left no time to play.

**Comment by audreytoskin** [comment]
I guess I'll close this issue for now, then; anyone interested in taking over development could comment here about their fork or something.
