### ISSUE TITLE
Support for GNOME 40 in Activities Configurator Extension

### ISSUE THREAD

**Issue by lozanotux** [nls1729/acme-code#82]
Hi, I've been using Activities Configurator extension on my productive laptop in my work. Is it possible to update this extension for gnome 40? I'm a Fedora user. Regards!
![ac_issue_g40](https://user-images.githubusercontent.com/6494902/118557529-b1456280-b73b-11eb-9e4e-120e78f535a8.png)

**Comment by nls1729** [comment]
@lozanotux 
It is possible.  The code is open source and can be modified by anyone who wants to maintain the extension.   I do not have the free time or energy necessary to maintain the extension.

**Comment by auipga** [comment]
@lozanotux 
Edit `~/.local/share/gnome-shell/extensions/extension-reloader@nls1729/metadata.json`
In line 9 change     `"3.36"` to     `"3.36", "40"`

**Comment by nls1729** [comment]
I no longer maintain the extension.  Changing the metadata.json does not resolve the inability to change the extension's preferences.
