### ISSUE TITLE
Extension settings won't open | Ubuntu 21.10 Impish Indri | Gnome 40.4.0

### ISSUE THREAD

**Issue by itsfranrose** [nls1729/acme-code#84]
Hi. I just upgraded my ubuntu and in the new gnome this error is given to me by Gnome Extensions.
`TypeError: noIconBox.pack_start is not a function

Stack trace:
  _init@/home/mehdi/.local/share/gnome-shell/extensions/activities-config@nls1729/prefs.js:100:19
  buildPrefsWidget@/home/mehdi/.local/share/gnome-shell/extensions/activities-config@nls1729/prefs.js:640:18
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
  `

**Comment by nls1729** [comment]
I no longer maintain the extension.
