### ISSUE TITLE
fedora 35 - doesn't work at all

### ISSUE THREAD

**Issue by roryst** [nls1729/acme-code#85]
Error: No property margin_left on GtkBox

Stack trace:
  _init/Gtk.Widget.prototype._init@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:47:50
  _init@/home/rory/.local/share/gnome-shell/extensions/donotdisturb-button@nls1729/prefs.js:104:27
  buildPrefsWidget@/home/rory/.local/share/gnome-shell/extensions/donotdisturb-button@nls1729/prefs.js:419:18
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:219:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:128:33
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17

**Comment by nls1729** [comment]
I no longer maintain this extension.  The following was posted on extensions.gnome.org on 2021-3-29.  I left the code here available to anyone who wants to port the code and maintain it. 

Do Not Disturb Button, donotdisturb-button@nls1729 - Effective March 29, 2021 the extension is NOT MAINTAINED. I give my permission to anyone who may want to become the maintainer. I no not have the free time or energy necessary to maintain the extension.
