### ISSUE TITLE
Extention crashes everytime the screen is locked in fedora. 

### ISSUE THREAD

**Issue by vikas-0** [nls1729/acme-code#9]
It crashes every time I lock and unlock the user. A simple restart by alt+f2 solves the problem for the time.
Using GNOME 2.18, using custom logo and no top left hot corner.

**Comment by nls1729** [comment]
Please see the attached file for ways to help debug the problem.  Let me know what you find.

Norman
[debug.txt](https://github.com/nls1729/acme-code/files/330341/debug.txt)

**Comment by vikas-0** [comment]
It seems that "No Top Left Hot Corner" was conflicting it. But disabling it didn't solved the problem. But after removing it, it seems that the problem is solved.
